/**
 * PLT and GOT Setup
 * ==================
 *
 * Manages the Procedure Linkage Table (PLT) and Global Offset Table (GOT)
 * for lazy symbol resolution and position-independent code.
 */

#include "linker.h"
#include <string.h>

/**
 * Initialize GOT (Global Offset Table)
 *
 * Sets up the first three GOT entries:
 * GOT[0] = address of dynamic section (for debugging)
 * GOT[1] = pointer to shared object structure (for resolver)
 * GOT[2] = address of resolver function
 *
 * @param so Shared object
 * @param resolver Address of lazy binding resolver function
 * @return 0 on success, negative error code on failure
 */
int plt_got_init(shared_object_t* so, uint64_t resolver) {
    if (!so || !so->pltgot) {
        return -1;
    }

    // GOT[0] = dynamic section address (optional, for debugging)
    so->pltgot[0] = 0;

    // GOT[1] = pointer to shared object (for resolver to identify which SO)
    so->pltgot[1] = (uint64_t)so;

    // GOT[2] = resolver function address
    so->pltgot[2] = resolver;

    linker_debug("Initialized GOT for %s: resolver=%p\n", so->name, (void*)resolver);

    return 0;
}

/**
 * PLT lazy binding resolver stub (assembly wrapper would call this)
 *
 * This function is called by the PLT stub when a function is called
 * for the first time. It resolves the symbol and updates the GOT entry.
 *
 * @param so Shared object (passed via GOT[1])
 * @param reloc_index Index of the relocation in JMPREL
 * @return Address of the resolved function
 */
uint64_t plt_lazy_resolver(shared_object_t* so, uint64_t reloc_index) {
    if (!so || !so->jmprel) {
        return 0;
    }

    linker_debug("PLT lazy resolver: %s, reloc_index=%lu\n", so->name, reloc_index);

    // Get the relocation entry
    elf64_rela_t* rela = NULL;
    if (so->pltrel == DT_RELA) {
        rela = &((elf64_rela_t*)so->jmprel)[reloc_index];
    } else {
        // REL relocations (less common)
        linker_debug("ERROR: REL PLT relocations not supported\n");
        return 0;
    }

    // Extract symbol index
    uint32_t sym_idx = ELF64_R_SYM(rela->r_info);
    elf64_sym_t* sym = &so->symtab[sym_idx];
    const char* sym_name = so->strtab + sym->st_name;

    linker_debug("  Symbol: %s\n", sym_name);

    // Look up symbol globally (we need the linker context)
    // NOTE: This is a simplification - we'd need to pass the context
    // For now, assume we have a global context pointer
    extern linker_context_t* g_linker_ctx;

    symbol_info_t* sym_info = linker_lookup_symbol_in_deps(g_linker_ctx, so, sym_name);
    if (!sym_info) {
        linker_debug("ERROR: Failed to resolve symbol %s\n", sym_name);
        return 0;
    }

    uint64_t sym_addr = linker_get_symbol_addr(sym_info->object, sym_info->symbol);
    linker_debug("  Resolved to: %p\n", (void*)sym_addr);

    // Update GOT entry
    uint64_t* got_entry = (uint64_t*)(so->base_addr + rela->r_offset);
    *got_entry = sym_addr;

    // Return the resolved address
    return sym_addr;
}

/**
 * Setup PLT for lazy binding
 *
 * This prepares the PLT stubs to jump to the resolver on first call.
 * The actual PLT code is typically generated by the compiler/linker,
 * but we need to initialize the GOT entries that the PLT uses.
 *
 * @param ctx Linker context
 * @param so Shared object
 * @return 0 on success, negative error code on failure
 */
int plt_setup_lazy_binding(linker_context_t* ctx, shared_object_t* so) {
    if (!ctx || !so) {
        return -1;
    }

    if (!so->jmprel || so->pltrelsz == 0) {
        return 0;  // No PLT
    }

    linker_debug("Setting up lazy binding for %s\n", so->name);

    // Initialize GOT with resolver
    uint64_t resolver_addr = (uint64_t)plt_lazy_resolver;
    int ret = plt_got_init(so, resolver_addr);
    if (ret < 0) {
        return ret;
    }

    // The PLT entries themselves are created by the linker at compile time
    // They contain code like:
    //   jmp *GOT[n]      ; Jump to address in GOT
    //   push reloc_index ; Push relocation index
    //   jmp PLT[0]       ; Jump to resolver stub
    //
    // PLT[0] (the first PLT entry) is special and jumps to the resolver:
    //   push GOT[1]      ; Push SO pointer
    //   jmp *GOT[2]      ; Jump to resolver
    //
    // We don't need to write this code - it's already in the binary.
    // We just need to ensure GOT[1] and GOT[2] are set correctly.

    return 0;
}

/**
 * Get PLT entry address for a symbol
 *
 * Finds the PLT entry for a given symbol (if it exists).
 *
 * @param so Shared object
 * @param sym_name Symbol name
 * @return Address of PLT entry, or 0 if not found
 */
uint64_t plt_get_entry_addr(shared_object_t* so, const char* sym_name) {
    if (!so || !sym_name || !so->jmprel) {
        return 0;
    }

    size_t num_plt;
    int is_rela = (so->pltrel == DT_RELA);

    if (is_rela) {
        num_plt = so->pltrelsz / sizeof(elf64_rela_t);
        elf64_rela_t* plt_rela = (elf64_rela_t*)so->jmprel;

        for (size_t i = 0; i < num_plt; i++) {
            uint32_t sym_idx = ELF64_R_SYM(plt_rela[i].r_info);
            elf64_sym_t* sym = &so->symtab[sym_idx];
            const char* name = so->strtab + sym->st_name;

            if (strcmp(name, sym_name) == 0) {
                // Found it - return the address where the GOT entry is
                // The PLT entry itself is at a fixed offset from the GOT entry
                return so->base_addr + plt_rela[i].r_offset;
            }
        }
    }

    return 0;
}

/**
 * Dump GOT contents (debugging)
 *
 * @param so Shared object
 * @param num_entries Number of GOT entries to dump
 */
void plt_got_dump(shared_object_t* so, size_t num_entries) {
    if (!so || !so->pltgot) {
        return;
    }

    linker_debug("GOT for %s:\n", so->name);
    for (size_t i = 0; i < num_entries && i < 64; i++) {
        linker_debug("  GOT[%zu] = 0x%016lx\n", i, so->pltgot[i]);
    }
}

/**
 * Check if address is in PLT
 *
 * @param so Shared object
 * @param addr Address to check
 * @return Non-zero if address is in PLT, zero otherwise
 */
int plt_is_plt_addr(shared_object_t* so, uint64_t addr) {
    if (!so || !so->pltgot) {
        return 0;
    }

    // PLT is typically located right before the GOT
    // This is a heuristic - proper implementation would parse section headers
    uint64_t got_addr = (uint64_t)so->pltgot;
    uint64_t plt_start = got_addr - 0x1000;  // Typical PLT size
    uint64_t plt_end = got_addr;

    return (addr >= plt_start && addr < plt_end);
}
