#!/usr/bin/env python3
"""
Embed RSA public key in bootloader header
Converts PEM public key to C array
"""

import sys
import struct
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend

def extract_rsa_components(pem_file):
    """Extract RSA modulus and exponent from PEM public key"""
    with open(pem_file, 'rb') as f:
        pem_data = f.read()

    pubkey = serialization.load_pem_public_key(pem_data, backend=default_backend())
    numbers = pubkey.public_numbers()

    # Get modulus (n) and exponent (e)
    n = numbers.n
    e = numbers.e
    key_size = pubkey.key_size

    # Convert to big-endian bytes
    n_bytes = n.to_bytes(key_size // 8, byteorder='big')

    return key_size, e, n_bytes

def generate_header(key_size, exponent, modulus, output_file):
    """Generate C header with embedded public key"""

    header = f"""/*
 * Embedded Public Key for Secure Boot
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by embed-pubkey.py
 */

#ifndef BOOT_PUBKEY_H
#define BOOT_PUBKEY_H

#include "boot_crypto.h"

// RSA-{key_size} Public Key
const boot_rsa_key_t BOOT_TRUSTED_KEY = {{
    .bits = {key_size},
    .e = {exponent},
    .n = {{
"""

    # Format modulus as C byte array
    for i in range(0, len(modulus), 16):
        chunk = modulus[i:i+16]
        hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
        header += f'        {hex_bytes}'
        if i + 16 < len(modulus):
            header += ','
        header += '\n'

    # Pad to maximum size (RSA-4096 = 512 bytes)
    if len(modulus) < 512:
        padding = 512 - len(modulus)
        header += '        ' + ', '.join(['0x00'] * padding) + '\n'

    header += """    }
};

#endif
"""

    with open(output_file, 'w') as f:
        f.write(header)

def main():
    if len(sys.argv) != 3:
        print("Usage: embed-pubkey.py <input-pubkey.pem> <output-header.h>")
        sys.exit(1)

    pem_file = sys.argv[1]
    output_file = sys.argv[2]

    print(f"Extracting public key from: {pem_file}")
    key_size, exponent, modulus = extract_rsa_components(pem_file)

    print(f"  Key size: {key_size} bits")
    print(f"  Exponent: {exponent}")
    print(f"  Modulus: {len(modulus)} bytes")

    print(f"Generating C header: {output_file}")
    generate_header(key_size, exponent, modulus, output_file)

    print("Done.")

if __name__ == '__main__':
    main()
