#!/usr/bin/env python3
"""Fetch Google Material Design icons (flat SVGs from jsDelivr), rasterize with
rsvg-convert, and emit them as embedded ARGB32 C arrays (white silhouettes) for
the compositor dock. Run once to (re)generate userspace/lib/icon/icon_assets.h.

  wsl -d Arch bash -lc 'cd /mnt/c/Users/wilde/Desktop/Kernel && python3 scripts/gen_icon_assets.py'

Network + rsvg-convert + Pillow required (gen-time only). The generated header
is checked into the tree and is all the build needs.
"""
import os, subprocess, sys
from PIL import Image

ROOT = "/mnt/c/Users/wilde/Desktop/Kernel"
OUT  = f"{ROOT}/userspace/lib/icon/icon_assets.h"
SZ   = 48
CDN  = "https://cdn.jsdelivr.net/npm/@material-design-icons/svg/filled/{}.svg"

# app key (matches icon_asset_for in icon.c) -> Material Symbols icon name
ICONS = {
    "terminal":   "terminal",
    "files":      "folder",
    "editor":     "description",
    "notes":      "sticky_note_2",
    "calculator": "calculate",
    "clock":      "schedule",
    "paint":      "palette",
    "games":      "sports_esports",
    "settings":   "settings",
    "calendar":   "calendar_month",
    "ide":        "account_tree",
    "sysmon":     "monitor_heart",
    "music":      "music_note",
}

def fetch_png(mname):
    svg = f"/tmp/mi_{mname}.svg"
    png = f"/tmp/mi_{mname}.png"
    url = CDN.format(mname)
    r = subprocess.run(["curl", "-sfL", "--max-time", "20", "-o", svg, url])
    if r.returncode != 0 or not os.path.exists(svg) or os.path.getsize(svg) < 40:
        return None
    r = subprocess.run(["rsvg-convert", "-w", str(SZ), "-h", str(SZ),
                        "-o", png, svg])
    if r.returncode != 0 or not os.path.exists(png):
        return None
    return png

def to_argb(png):
    im = Image.open(png).convert("RGBA").resize((SZ, SZ), Image.LANCZOS)
    px = im.load()
    out = []
    for y in range(SZ):
        for x in range(SZ):
            r, g, b, a = px[x, y]
            # white silhouette: keep coverage in alpha, force RGB white so the
            # compositor can tint it onto any accent tile.
            out.append((a << 24) | 0x00FFFFFF if a else 0)
    return out

def main():
    assets = {}
    for key, mname in ICONS.items():
        png = fetch_png(mname)
        if not png:
            print(f"  WARN: failed {key} ({mname})", file=sys.stderr)
            continue
        assets[key] = to_argb(png)
        print(f"  ok: {key} <- {mname}")
    if not assets:
        print("no icons fetched", file=sys.stderr); sys.exit(1)

    with open(OUT, "w") as f:
        f.write("/* AUTO-GENERATED by scripts/gen_icon_assets.py -- do not edit.\n")
        f.write(" * Google Material Design icons (Apache-2.0), white silhouettes,\n")
        f.write(f" * {SZ}x{SZ} ARGB32, tinted onto the app accent tile by icon.c. */\n")
        f.write("#ifndef ICON_ASSETS_H\n#define ICON_ASSETS_H\n#include <stdint.h>\n")
        f.write(f"#define ICON_ASSET_SZ {SZ}\n\n")
        for key, arr in assets.items():
            f.write(f"static const uint32_t ICON_ASSET_{key}[{SZ}*{SZ}] = {{")
            for i, v in enumerate(arr):
                if i % 12 == 0:
                    f.write("\n")
                f.write(f"0x{v:08X}," if v else "0,")
            f.write("\n};\n\n")
        f.write("typedef struct { const char* key; const uint32_t* px; } IconAsset;\n")
        f.write("static const IconAsset ICON_ASSETS[] = {\n")
        for key in assets:
            f.write(f'    {{ "{key}", ICON_ASSET_{key} }},\n')
        f.write("    { 0, 0 }\n};\n\n#endif /* ICON_ASSETS_H */\n")
    print(f"wrote {OUT} ({len(assets)} icons, {os.path.getsize(OUT)} bytes)")

if __name__ == "__main__":
    main()
