#!/usr/bin/env python3
# gen_img_fixtures.py -- BROWSER2-IMG-0: deterministic image fixtures.
#
# Writes into <outdir> (default /tmp/ird/etc/imgtest):
#   t.png        8x8 solid red      (PNG: 8-bit RGB, non-interlaced, filter 0)
#   t.gif        8x8 solid green    (GIF89a, 2-entry GCT, clear-per-pixel LZW)
#   t.bmp        8x8 solid blue     (BMP: 24-bit BITMAPINFOHEADER, bottom-up)
#   big.png      1000x800 solid     (wider than the 800px viewport -> the
#                                    bounded/clipped acceptance case; solid
#                                    color so zlib keeps it tiny)
#   (missing.png is deliberately NOT written -- the placeholder case)
#
# Everything stays inside what userspace/lib/imgcodec actually decodes:
# PNG color type 2 @ 8-bit non-interlaced; GIF87a/89a single image with a
# global color table; BMP 24-bit uncompressed. The GIF encoder emits a CLEAR
# code before every pixel code so the LZW dictionary never grows -- valid
# LZW, zero encoder cleverness to get wrong.
import struct, sys, zlib, os

def png_chunk(tag, data):
    return (struct.pack(">I", len(data)) + tag + data +
            struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

def make_png(w, h, rgb):
    row = b"\x00" + bytes(rgb) * w                 # filter 0 + RGB pixels
    raw = row * h
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)   # 8-bit, RGB
    return (b"\x89PNG\r\n\x1a\n" +
            png_chunk(b"IHDR", ihdr) +
            png_chunk(b"IDAT", zlib.compress(raw, 9)) +
            png_chunk(b"IEND", b""))

def make_gif(w, h, rgb):
    # GIF89a, global color table with 2 entries (color 0 = the fill color).
    hdr = b"GIF89a" + struct.pack("<HH", w, h) + bytes([0x80, 0, 0])
    gct = bytes(rgb) + b"\x00\x00\x00"
    img = b"\x2C" + struct.pack("<HHHH", 0, 0, w, h) + b"\x00"
    min_code = 2                       # GIF minimum LZW code size
    clear, eoi, codebits = 1 << min_code, (1 << min_code) + 1, min_code + 1
    out, cur, bits = bytearray(), 0, 0
    def emit(code):
        nonlocal cur, bits
        cur |= code << bits
        bits += codebits
        while bits >= 8:
            out.append(cur & 0xFF); cur >>= 8; bits -= 8
    for _ in range(w * h):
        emit(clear); emit(0)           # reset dict, then pixel index 0
    emit(eoi)
    if bits: out.append(cur & 0xFF)
    data = bytes([min_code])
    pos = 0
    while pos < len(out):              # <=255-byte sub-blocks
        chunk = bytes(out[pos:pos + 255]); pos += 255
        data += bytes([len(chunk)]) + chunk
    return hdr + gct + img + data + b"\x00" + b"\x3B"

def make_bmp(w, h, rgb):
    rowbytes = w * 3
    pad = (4 - rowbytes % 4) % 4
    px = (bytes([rgb[2], rgb[1], rgb[0]]) * w + b"\x00" * pad) * h
    off = 14 + 40
    hdr = (b"BM" + struct.pack("<IHHI", off + len(px), 0, 0, off) +
           struct.pack("<IiiHHIIiiII", 40, w, h, 1, 24, 0, len(px), 2835, 2835, 0, 0))
    return hdr + px

C_HEADER_TOP = """\
/* b2_img_fixtures.h -- GENERATED by scripts/gen_img_fixtures.py. Do not edit.
 *
 * BROWSER2-IMG-0 acceptance fixtures embedded as byte arrays. The same
 * bytes are also staged into the initrd at /etc/imgtest/, but in-OS VFS
 * reads of initrd-backed files return ZEROS inside mmap-heavy processes
 * (a pre-existing per-process address-space aliasing kernel bug -- see
 * the BROWSER2-IMG-0 brick record), so the about:imgtest page sources
 * these embedded copies via the "fixture:" scheme instead. */
"""

def c_array(name, data):
    lines = [f"static const unsigned char {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(str(b) for b in data[i:i+16]) + ",")
    lines.append("};")
    return "\n".join(lines)

def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "/tmp/ird/etc/imgtest"
    header = sys.argv[2] if len(sys.argv) > 2 else None
    os.makedirs(outdir, exist_ok=True)
    files = {
        "t.png":   make_png(8, 8, (200, 30, 30)),
        "t.gif":   make_gif(8, 8, (30, 170, 60)),
        "t.bmp":   make_bmp(8, 8, (40, 70, 200)),
        "big.png": make_png(1000, 800, (60, 110, 180)),
    }
    for name, data in files.items():
        with open(os.path.join(outdir, name), "wb") as f:
            f.write(data)
        print(f"[imgfixtures] {name}: {len(data)} bytes")
    if header:
        ident = {n: "b2fix_" + n.replace(".", "_") for n in files}
        parts = [C_HEADER_TOP]
        for n, d in files.items():
            parts.append(c_array(ident[n], d))
        parts.append("""
typedef struct { const char *name; const unsigned char *data; unsigned long len; } b2_fixture_t;
static const b2_fixture_t B2_FIXTURES[] = {
""" + "".join(f'    {{ "{n}", {ident[n]}, {len(d)}UL }},\n' for n, d in files.items()) + "};\n")
        with open(header, "w", newline="\n") as f:
            f.write("\n".join(parts))
        print(f"[imgfixtures] header: {header}")

if __name__ == "__main__":
    main()
