#!/usr/bin/env python3
"""Extract the RFC 8448 Section 3 server encrypted-flight plaintext (657 octets)
and ciphertext record (679 octets) into a C header for the TLS 1.3 record-layer
KAT. Reliable: collects exactly N hex tokens after each labeled block and asserts
the count, so a mis-parse fails loudly instead of producing wrong bytes."""
import re, sys, urllib.request, os

URL = "https://www.rfc-editor.org/rfc/rfc8448.txt"
TXT = "/tmp/rfc8448.txt"
OUT = os.path.join(os.path.dirname(__file__), "rfc8448_record_vec.h")

if not os.path.exists(TXT):
    urllib.request.urlretrieve(URL, TXT)
lines = open(TXT).read().splitlines()

def extract(label_re, want):
    """Find the line matching label_re, then collect exactly `want` hex byte
    tokens from after the colon and following continuation lines."""
    for i, ln in enumerate(lines):
        if re.search(label_re, ln):
            after = ln.split(":", 1)[1] if ":" in ln else ""
            toks = re.findall(r"\b[0-9a-f]{2}\b", after)
            j = i + 1
            while len(toks) < want and j < len(lines):
                # stop if we hit the next labeled block
                if re.search(r"\(\d+ octets\)", lines[j]):
                    break
                toks += re.findall(r"\b[0-9a-f]{2}\b", lines[j])
                j += 1
            if len(toks) != want:
                sys.exit(f"FATAL: '{label_re}' got {len(toks)} tokens, want {want}")
            return bytes(int(t, 16) for t in toks)
    sys.exit(f"FATAL: label '{label_re}' not found")

# The server flight is the FIRST occurrence (Section 3). payload(657)=plaintext,
# complete record(679)=ciphertext; they appear consecutively (lines ~457/~490).
plain = extract(r"payload \(657 octets\)", 657)
rec   = extract(r"complete record \(679 octets\)", 679)

# sanity: record = 5 (hdr) + 658 (plaintext+type) + 16 (tag) = 679
assert rec[:3] == bytes([0x17, 0x03, 0x03]), "record header"
hdr_len = (rec[3] << 8) | rec[4]
assert hdr_len == 679 - 5, f"record length field {hdr_len}"
assert len(plain) == 657 and len(rec) == 679

def carr(name, data):
    out = f"static const unsigned char {name}[] = {{\n"
    for k in range(0, len(data), 12):
        out += "    " + ", ".join(f"0x{b:02x}" for b in data[k:k+12]) + ",\n"
    out += "};\n" + f"static const unsigned long {name}_len = {len(data)};\n"
    return out

with open(OUT, "w") as f:
    f.write("/* RFC 8448 Section 3 server encrypted flight -- generated by\n"
            " * build_test/extract_rfc8448_record.py. Plaintext (657) + wire\n"
            " * ciphertext record (679). For the TLS 1.3 record-layer KAT. */\n")
    f.write("#ifndef RFC8448_RECORD_VEC_H\n#define RFC8448_RECORD_VEC_H\n\n")
    f.write(carr("rfc8448_server_flight_plain", plain) + "\n")
    f.write(carr("rfc8448_server_flight_record", rec) + "\n")
    f.write("#endif\n")
print(f"wrote {OUT}: plaintext={len(plain)} record={len(rec)} (header len field={hdr_len})")
