/* Host harness for the TLS 1.3 record-layer KAT (build_test/tls13_record_kat.sh).
 * Decrypts the REAL RFC 8448 Section 3 server encrypted flight with the RFC's
 * server handshake key/iv and checks it matches the published plaintext, then
 * runs the seal/open round-trip selftest. */
#include <stdio.h>
#include "../userspace/lib/tls/tls13_record.h"
#include "rfc8448_record_vec.h"   /* generated by extract_rfc8448_record.py */

/* RFC 8448 Section 3 server handshake traffic key + iv (also derived + KAT'd by
 * tls13_keysched_selftest). */
static const unsigned char SKEY[16] = {
    0x3f,0xce,0x51,0x60,0x09,0xc2,0x17,0x27,0xd0,0xf2,0xe4,0xe8,0x6e,0xe4,0x03,0xbc };
static const unsigned char SIV[12]  = {
    0x5d,0x31,0x3e,0xb2,0x67,0x12,0x76,0xee,0x13,0x00,0x0b,0x30 };

int main(void)
{
    int pass = 1;
    unsigned char out[1024];
    unsigned long olen;
    unsigned char itype;

    /* (1) The decisive interop KAT: decrypt the real RFC 8448 server flight. */
    int rc = tls13_record_open(TLS13_AEAD_AES128_GCM, SKEY, SIV, /*seq=*/0,
                               rfc8448_server_flight_record,
                               rfc8448_server_flight_record_len,
                               out, sizeof(out), &olen, &itype);
    if (rc != 0) { printf("  FAIL record_open rc=%d\n", rc); pass = 0; }
    else if (itype != 0x16) { printf("  FAIL inner type 0x%02x != 0x16\n", itype); pass = 0; }
    else if (olen != rfc8448_server_flight_plain_len) {
        printf("  FAIL inner len %lu != %lu\n", olen, rfc8448_server_flight_plain_len); pass = 0;
    } else {
        int same = 1;
        for (unsigned long i = 0; i < olen; i++)
            if (out[i] != rfc8448_server_flight_plain[i]) { same = 0; break; }
        if (!same) { printf("  FAIL decrypted plaintext != RFC 8448 plaintext\n"); pass = 0; }
        else printf("  ok   RFC 8448 server flight decrypts to the exact published "
                    "plaintext (%lu octets, inner type=handshake)\n", olen);
    }

    /* (2) seal/open round-trip across all three AEADs + wrong-seq rejection. */
    int s = tls13_record_selftest();
    if (s != 0) { printf("  FAIL record selftest step %d\n", s); pass = 0; }
    else printf("  ok   seal/open round-trip (AES-128/256-GCM + ChaCha20) + wrong-seq rejected\n");

    printf(pass ? "TLS13RECKAT: PASS\n" : "TLS13RECKAT: FAIL\n");
    return pass ? 0 : 1;
}
