"""Meridian shell -- launch-FX sprite baker (headless Blender):

  blender -b --factory-startup --python tools/blender/meridian_sprites.py -- <out_dir>

Produces, for the app-launch effect ("ribbon + chain swirl, sparkle when it opens correctly"):
  chain_links.la8   32 sprites of a real 3D metallic chain link, 48x48, 2 bytes/px (L, A):
                    variant 0 = face-on, variant 1 = tilted ~68 deg (reads as the interlocking neighbour),
                    16 in-plane orientations each (0..168.75 deg; a stadium link is 180-degree symmetric)
  sparkle.a8        3 four-point star glints (16/24/32 px), alpha only (additive blend + tint at runtime)
  halo.a8           96x96 radial focus/launch glow, alpha only
  glass9.rgba       96x96 glass tile (premultiplied RGBA) for 9-slice scaling
plus a *_preview.png for each. Original art generated by this script; nothing copied from any product.
The chain link is rendered in Blender (real geometry, fixed-light shading); halo/glints/glass are procedural.
"""
import math
import os
import sys

import bpy
import bmesh
import numpy as np

OUT = os.path.abspath(sys.argv[sys.argv.index("--") + 1] if "--" in sys.argv else "build/meridian")  # ABSOLUTE path
os.makedirs(OUT, exist_ok=True)

SPR = 48                 # final sprite size
SS = 4                   # render at 192x192, box-filter down
N_ROT, TILTS = 16, (0.0, math.radians(68.0))


# ----------------------------------------------------------------------------- the chain link (real 3D)
def stadium_path(L=1.0, R=0.38, n=96):
    pts = []
    per = 2 * L + 2 * math.pi * R
    for i in range(n):
        s = per * i / n
        if s < L:                                     # top straight, left -> right
            pts.append((-L / 2 + s, R))
        elif s < L + math.pi * R:                     # right semicircle
            a = math.pi / 2 - (s - L) / R
            pts.append((L / 2 + R * math.cos(a), R * math.sin(a)))
        elif s < 2 * L + math.pi * R:                 # bottom straight, right -> left
            pts.append((L / 2 - (s - L - math.pi * R), -R))
        else:                                         # left semicircle
            a = -math.pi / 2 - (s - 2 * L - math.pi * R) / R
            pts.append((-L / 2 + R * math.cos(a), R * math.sin(a)))
    return pts


def build_link():
    pts = stadium_path()
    t_r, nsec = 0.12, 14
    bm = bmesh.new()
    rings = []
    n = len(pts)
    for i, (x, y) in enumerate(pts):
        nx, ny = pts[(i + 1) % n][0] - pts[(i - 1) % n][0], pts[(i + 1) % n][1] - pts[(i - 1) % n][1]
        tl = math.hypot(nx, ny) or 1.0
        tx, ty = nx / tl, ny / tl                    # tangent in the XY plane
        ox, oy = -ty, tx                             # in-plane normal of the path
        ring = []
        for k in range(nsec):
            a = 2 * math.pi * k / nsec
            ring.append(bm.verts.new((x + ox * t_r * math.cos(a), y + oy * t_r * math.cos(a), t_r * math.sin(a))))
        rings.append(ring)
    for i in range(n):
        for k in range(nsec):
            bm.faces.new((rings[i][k], rings[i][(k + 1) % nsec], rings[(i + 1) % n][(k + 1) % nsec], rings[(i + 1) % n][k]))
    me = bpy.data.meshes.new("link")
    bm.to_mesh(me)
    bm.free()
    for p in me.polygons:
        p.use_smooth = True
    ob = bpy.data.objects.new("link", me)
    bpy.context.scene.collection.objects.link(ob)
    return ob


def vm(nt, op, a=None, b=None):
    n = nt.nodes.new("ShaderNodeVectorMath")
    n.operation = op
    if a is not None:
        nt.links.new(a, n.inputs[0]) if not isinstance(a, tuple) else n.inputs[0].default_value.__setitem__(slice(0, 3), a)
    if b is not None:
        nt.links.new(b, n.inputs[1]) if not isinstance(b, tuple) else n.inputs[1].default_value.__setitem__(slice(0, 3), b)
    return n


def mm(nt, op, a=None, b=None, clamp=False):
    n = nt.nodes.new("ShaderNodeMath")
    n.operation = op
    n.use_clamp = clamp
    for idx, v in ((0, a), (1, b)):
        if v is None:
            continue
        if isinstance(v, (int, float)):
            n.inputs[idx].default_value = float(v)
        else:
            nt.links.new(v, n.inputs[idx])
    return n


def link_material():
    m = bpy.data.materials.new("link_shade")
    m.use_nodes = True
    nt = m.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    emi = nt.nodes.new("ShaderNodeEmission")
    geo = nt.nodes.new("ShaderNodeNewGeometry")
    N = geo.outputs["Normal"]
    Ld = (-0.40, 0.62, 0.68)
    ll = math.sqrt(sum(c * c for c in Ld))
    Ld = tuple(c / ll for c in Ld)
    diff = mm(nt, "MAXIMUM", vm(nt, "DOT_PRODUCT", N, Ld).outputs["Value"], 0.0)
    H = (Ld[0], Ld[1], Ld[2] + 1.0)
    hl = math.sqrt(sum(c * c for c in H))
    H = tuple(c / hl for c in H)
    sdot = mm(nt, "MAXIMUM", vm(nt, "DOT_PRODUCT", N, H).outputs["Value"], 0.0)
    spec = mm(nt, "POWER", sdot.outputs["Value"], 38.0)
    facing = vm(nt, "DOT_PRODUCT", N, (0.0, 0.0, 1.0))
    rim = mm(nt, "POWER", mm(nt, "SUBTRACT", 1.0, mm(nt, "ABSOLUTE", facing.outputs["Value"]).outputs["Value"]).outputs["Value"], 2.4)
    s = mm(nt, "MULTIPLY", mm(nt, "POWER", diff.outputs["Value"], 1.4).outputs["Value"], 0.55)
    s = mm(nt, "ADD", s.outputs["Value"], mm(nt, "MULTIPLY", spec.outputs["Value"], 0.95).outputs["Value"])
    s = mm(nt, "ADD", s.outputs["Value"], mm(nt, "MULTIPLY", rim.outputs["Value"], 0.45).outputs["Value"])
    s = mm(nt, "ADD", s.outputs["Value"], 0.20, clamp=True)
    comb = nt.nodes.new("ShaderNodeCombineColor")
    for ch in ("Red", "Green", "Blue"):
        nt.links.new(s.outputs["Value"], comb.inputs[ch])
    nt.links.new(comb.outputs["Color"], emi.inputs["Color"])
    nt.links.new(emi.outputs["Emission"], out.inputs["Surface"])
    m.use_backface_culling = False
    return m


def setup_scene():
    sc = bpy.context.scene
    for ob in list(sc.objects):
        bpy.data.objects.remove(ob, do_unlink=True)
    R = SPR * SS
    sc.render.resolution_x = sc.render.resolution_y = R
    sc.render.resolution_percentage = 100
    sc.render.film_transparent = True
    sc.render.image_settings.file_format = "PNG"
    sc.render.image_settings.color_mode = "RGBA"
    try:
        sc.view_settings.view_transform = "Standard"
    except TypeError:
        pass
    engines = [i.identifier for i in sc.render.bl_rna.properties["engine"].enum_items]
    sc.render.engine = "BLENDER_EEVEE" if "BLENDER_EEVEE" in engines else engines[0]
    cam = bpy.data.cameras.new("cam")
    cam.type = "ORTHO"
    cam.ortho_scale = 2.5
    co = bpy.data.objects.new("cam", cam)
    sc.collection.objects.link(co)
    co.location = (0, 0, 20)
    sc.camera = co
    return sc


def render_px(sc, path):
    sc.render.filepath = path
    bpy.ops.render.render(write_still=True)
    img = bpy.data.images.load(path)
    w, h = img.size
    a = np.array(img.pixels[:], dtype=np.float32).reshape(h, w, 4)[::-1]
    bpy.data.images.remove(img)
    os.remove(path)
    return a


def bake_chain(sc):
    ob = build_link()
    ob.data.materials.append(link_material())
    la = []
    prev = np.zeros((SPR * 2, SPR * N_ROT, 4), dtype=np.float32)
    for vi, tilt in enumerate(TILTS):
        for r in range(N_ROT):
            phi = math.pi * r / N_ROT
            ob.rotation_mode = "ZYX"
            ob.rotation_euler = (tilt, 0.0, phi)           # tilt about X first, then spin about Z (screen plane)
            px = render_px(sc, os.path.join(OUT, "_l.png"))
            alpha = px[..., 3]
            lum = np.where(alpha > 1e-4, px[..., 0] / np.maximum(alpha, 1e-4), 0.0)
            A = alpha.reshape(SPR, SS, SPR, SS).mean(axis=(1, 3))
            L = (lum * alpha).reshape(SPR, SS, SPR, SS).mean(axis=(1, 3)) / np.maximum(A, 1e-4)
            L = np.clip(L, 0, 1)
            la.append(np.stack([(L * 255 + 0.5).astype(np.uint8), (np.clip(A, 0, 1) * 255 + 0.5).astype(np.uint8)], axis=-1))
            prev[vi * SPR:(vi + 1) * SPR, r * SPR:(r + 1) * SPR, 0:3] = L[..., None]
            prev[vi * SPR:(vi + 1) * SPR, r * SPR:(r + 1) * SPR, 3] = A
    np.concatenate([x.reshape(-1) for x in la]).tofile(os.path.join(OUT, "chain_links.la8"))
    save_png("chain_links_preview.png", prev)
    bpy.data.objects.remove(ob, do_unlink=True)
    print("CHAIN: 32 sprites %dx%d -> chain_links.la8 (%d bytes)" % (SPR, SPR, 32 * SPR * SPR * 2))


# ----------------------------------------------------------------------------- procedural sprites
def save_png(name, rgba):
    h, w, _ = rgba.shape
    img = bpy.data.images.new(name, w, h, alpha=True)
    img.pixels = np.clip(rgba, 0, 1)[::-1].reshape(-1).tolist()
    img.filepath_raw = os.path.join(OUT, name)
    img.file_format = "PNG"
    img.save()
    bpy.data.images.remove(img)


def bake_sparkle():
    sizes = (16, 24, 32)
    blobs = []
    prev = np.zeros((32, sum(sizes), 4), dtype=np.float32)
    x0 = 0
    for s in sizes:
        c = (s - 1) / 2.0
        yy, xx = np.mgrid[0:s, 0:s].astype(np.float32)
        dx, dy = (xx - c) / (s / 2.0), (yy - c) / (s / 2.0)
        r = np.hypot(dx, dy)
        core = np.exp(-(r * 3.4) ** 2)                              # tight bright core
        h = np.exp(-(np.abs(dy) * 9.0)) * np.exp(-(np.abs(dx) * 2.1))  # horizontal streak
        v = np.exp(-(np.abs(dx) * 9.0)) * np.exp(-(np.abs(dy) * 2.1))  # vertical streak
        d1 = np.exp(-(np.abs(dx - dy) * 7.0)) * np.exp(-(np.abs(dx + dy) * 3.2)) * 0.45   # faint diagonals
        d2 = np.exp(-(np.abs(dx + dy) * 7.0)) * np.exp(-(np.abs(dx - dy) * 3.2)) * 0.45
        a = np.clip(core + 0.85 * (h + v) + d1 + d2, 0, 1)
        a = a * np.clip(1.15 - r, 0, 1)                             # fade to nothing at the edge
        blobs.append((a * 255 + 0.5).astype(np.uint8))
        prev[0:s, x0:x0 + s, 0:3] = a[..., None]
        prev[0:s, x0:x0 + s, 3] = a
        x0 += s
    np.concatenate([b.reshape(-1) for b in blobs]).tofile(os.path.join(OUT, "sparkle.a8"))
    save_png("sparkle_preview.png", prev)
    print("SPARKLE: sizes", sizes, "-> sparkle.a8")


def bake_halo():
    s = 96
    c = (s - 1) / 2.0
    yy, xx = np.mgrid[0:s, 0:s].astype(np.float32)
    r = np.hypot(xx - c, yy - c) / (s / 2.0)
    a = np.clip(np.exp(-(r * 2.6) ** 2) * 0.9 + np.exp(-(r * 1.5)) * 0.18, 0, 1) * np.clip(1.08 - r, 0, 1) ** 1.4
    (a * 255 + 0.5).astype(np.uint8).tofile(os.path.join(OUT, "halo.a8"))
    prev = np.zeros((s, s, 4), dtype=np.float32)
    prev[..., 0:3] = a[..., None]
    prev[..., 3] = a
    save_png("halo_preview.png", prev)
    print("HALO: 96x96 -> halo.a8")


def bake_glass():
    s, rad = 96, 14.0
    yy, xx = np.mgrid[0:s, 0:s].astype(np.float32)
    # signed distance to a rounded rect inset by 1 px
    qx, qy = np.abs(xx - (s - 1) / 2) - ((s - 1) / 2 - rad - 1), np.abs(yy - (s - 1) / 2) - ((s - 1) / 2 - rad - 1)
    sd = np.hypot(np.maximum(qx, 0), np.maximum(qy, 0)) + np.minimum(np.maximum(qx, qy), 0) - rad
    cover = np.clip(0.5 - sd, 0, 1)                                   # anti-aliased edge
    t = yy / (s - 1)
    base = 0.10 + 0.05 * (1 - t)                                      # faint body tint (white @ 10-15 %)
    sheen = np.clip(0.20 * (1 - np.clip(t / 0.5, 0, 1)) ** 1.6, 0, 1)  # top-half gloss, 18-20 % -> 0 by mid-height
    top_hi = (np.abs(yy - 1.5) < 0.9).astype(np.float32) * 0.32 * np.clip(-sd - 2, 0, 1)   # 1 px top highlight
    bot_lo = (np.abs(yy - (s - 2.5)) < 0.9).astype(np.float32) * 0.22                      # 1 px bottom line (dark)
    rim = np.exp(-np.abs(sd + 0.6) * 1.4) * 0.16                      # thin edge glow
    white = np.clip((base + sheen + top_hi + rim) * cover, 0, 1)
    dark = np.clip(bot_lo * cover, 0, 1)
    a = np.clip(white + dark, 0, 1)
    lum = np.where(a > 1e-4, white / np.maximum(a, 1e-4), 0)          # white-ish where glass, black on the dark line
    rgba = np.stack([lum, lum, lum, a], axis=-1)
    prem = np.concatenate([rgba[..., 0:3] * rgba[..., 3:4], rgba[..., 3:4]], axis=-1)
    (np.clip(prem, 0, 1) * 255 + 0.5).astype(np.uint8).tofile(os.path.join(OUT, "glass9.rgba"))
    save_png("glass9_preview.png", rgba)
    print("GLASS: 96x96 premultiplied RGBA -> glass9.rgba")


def main():
    sc = setup_scene()
    bake_chain(sc)
    bake_sparkle()
    bake_halo()
    bake_glass()
    print("MERIDIAN-SPRITES: done ->", OUT)


main()
