"""Meridian shell -- ribbon layer baker (run headless):

  "C:/Program Files/Blender Foundation/Blender 5.0/blender.exe" -b --factory-startup \
      --python tools/blender/meridian_ribbons.py -- <out_dir>

Models three flowing translucent ribbons as REAL 3D twisted bands, renders each orthographically and bakes
two channels the OS compositor can blit cheaply and tint at runtime:
    L = shaded intensity (how the twisting surface catches light)     A = soft coverage
The geometry is PERIODIC (integer sine cycles over one frame width) and the camera is orthographic, so every
layer tiles seamlessly left-to-right -- the OS scrolls them for the endless drift + parallax.

Output (per layer, 320x180, 2 bytes/px "LA8"): ribbon_<a|b|c>.png (RGBA preview) and ribbon_<a|b|c>.la8.
Original art generated by this script; nothing is copied from any other product.
"""
import math
import os
import sys

import bpy
import bmesh

OUT = os.path.abspath(sys.argv[sys.argv.index("--") + 1] if "--" in sys.argv else "build/meridian")   # ABSOLUTE: Blender resolves relative paths against the drive root
os.makedirs(OUT, exist_ok=True)

W_OUT, H_OUT = 320, 180
SS = 3                                   # supersample: render at 960x540, box-filter down
RW, RH = W_OUT * SS, H_OUT * SS
LX = 16.0                                # world width of one period
LY = LX * H_OUT / W_OUT

# (layer id, parameters). All k* are INTEGER cycle counts per period => seamless tiling.
LAYERS = {
    "a": dict(seed=1, y0=+0.10, A1=2.6, k1=1, p1=0.10, A2=0.9, k2=2, p2=0.55, Z=1.8, kz=1, pz=0.30,
              T=1.9, kt=2, pt=0.15, W=3.4, kw=1, pw=0.40),
    "b": dict(seed=2, y0=-0.55, A1=2.0, k1=2, p1=0.70, A2=1.1, k2=3, p2=0.20, Z=2.2, kz=1, pz=0.80,
              T=2.4, kt=1, pt=0.60, W=2.6, kw=2, pw=0.10),
    "c": dict(seed=3, y0=+0.45, A1=1.4, k1=1, p1=0.45, A2=0.7, k2=3, p2=0.90, Z=1.2, kz=2, pz=0.05,
              T=1.5, kt=3, pt=0.35, W=2.0, kw=1, pw=0.75),
}


def tau(x):
    return 2.0 * math.pi * x


def build_ribbon(p, name):
    """Twisted flat band along x in [-1, 2) periods (3 periods, so the camera crop never sees an end)."""
    nseg, nacross = 480, 14
    bm = bmesh.new()
    rows = []
    for i in range(nseg + 1):
        t = -1.0 + 3.0 * i / nseg                      # -1 .. 2
        cx = (t - 0.5) * LX                            # centred on the frame
        cy = p["y0"] * LY * 0.25 + p["A1"] * math.sin(tau(p["k1"] * t + p["p1"])) \
            + p["A2"] * math.sin(tau(p["k2"] * t + p["p2"]))
        cz = p["Z"] * math.sin(tau(p["kz"] * t + p["pz"]))
        th = p["T"] * math.sin(tau(p["kt"] * t + p["pt"])) * 1.4      # twist angle (radians) about the tangent
        w = p["W"] * (1.0 + 0.38 * math.sin(tau(p["kw"] * t + p["pw"])))
        # tangent (numerical derivative of the centreline)
        e = 1e-4
        def cl(tt):
            return ((tt - 0.5) * LX,
                    p["y0"] * LY * 0.25 + p["A1"] * math.sin(tau(p["k1"] * tt + p["p1"])) + p["A2"] * math.sin(tau(p["k2"] * tt + p["p2"])),
                    p["Z"] * math.sin(tau(p["kz"] * tt + p["pz"])))
        a0, a1 = cl(t - e), cl(t + e)
        tx, ty, tz = (a1[0] - a0[0]), (a1[1] - a0[1]), (a1[2] - a0[2])
        tl = math.sqrt(tx * tx + ty * ty + tz * tz) or 1.0
        tx, ty, tz = tx / tl, ty / tl, tz / tl
        # base binormal = tangent x forward(0,0,1)-ish, then rotate by the twist angle about the tangent
        bx, by, bz = ty * 1 - tz * 0, -(tx * 1 - tz * 0), 0.0       # (tangent) x (0,0,1)
        bl = math.sqrt(bx * bx + by * by + bz * bz) or 1.0
        bx, by, bz = bx / bl, by / bl, bz / bl
        # second axis = tangent x binormal
        nx, ny, nz = ty * bz - tz * by, tz * bx - tx * bz, tx * by - ty * bx
        c, s = math.cos(th), math.sin(th)
        ux, uy, uz = bx * c + nx * s, by * c + ny * s, bz * c + nz * s
        row = []
        for j in range(nacross + 1):
            u = (j / nacross - 0.5) * w
            row.append(bm.verts.new((cx + ux * u, cy + uy * u, cz + uz * u)))
        rows.append(row)
    for i in range(nseg):
        for j in range(nacross):
            bm.faces.new((rows[i][j], rows[i][j + 1], rows[i + 1][j + 1], rows[i + 1][j]))
    me = bpy.data.meshes.new(name)
    bm.to_mesh(me)
    bm.free()
    ob = bpy.data.objects.new(name, me)
    bpy.context.scene.collection.objects.link(ob)
    for poly in me.polygons:
        poly.use_smooth = True
    return ob


def shader_material():
    """Emission whose brightness follows how the surface faces a fixed (view-space) light: a periodic,
    position-independent look, so the layer tiles. Double-sided by construction (no backface culling)."""
    m = bpy.data.materials.new("ribbon_shade")
    m.use_nodes = True
    nt = m.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    emi = nt.nodes.new("ShaderNodeEmission")
    geo = nt.nodes.new("ShaderNodeNewGeometry")
    dot = nt.nodes.new("ShaderNodeVectorMath")
    dot.operation = "DOT_PRODUCT"
    dot.inputs[1].default_value = (-0.45, 0.62, 0.64)           # fixed key light direction (world == view)
    absn = nt.nodes.new("ShaderNodeMath")
    absn.operation = "ABSOLUTE"
    pw = nt.nodes.new("ShaderNodeMath")
    pw.operation = "POWER"
    pw.inputs[1].default_value = 1.15
    mul = nt.nodes.new("ShaderNodeMath")
    mul.operation = "MULTIPLY"
    mul.inputs[1].default_value = 0.78
    add = nt.nodes.new("ShaderNodeMath")
    add.operation = "ADD"
    add.inputs[1].default_value = 0.34                           # ambient floor: soft, translucent look -- no band goes near-black
    clamp = nt.nodes.new("ShaderNodeClamp")
    comb = nt.nodes.new("ShaderNodeCombineColor")
    nt.links.new(geo.outputs["Normal"], dot.inputs[0])
    nt.links.new(dot.outputs["Value"], absn.inputs[0])
    nt.links.new(absn.outputs["Value"], pw.inputs[0])
    nt.links.new(pw.outputs["Value"], mul.inputs[0])
    nt.links.new(mul.outputs["Value"], add.inputs[0])
    nt.links.new(add.outputs["Value"], clamp.inputs["Value"])
    for ch in ("Red", "Green", "Blue"):
        nt.links.new(clamp.outputs["Result"], comb.inputs[ch])
    nt.links.new(comb.outputs["Color"], emi.inputs["Color"])
    nt.links.new(emi.outputs["Emission"], out.inputs["Surface"])
    m.use_backface_culling = False
    return m


def setup_scene():
    sc = bpy.context.scene
    for ob in list(sc.objects):
        bpy.data.objects.remove(ob, do_unlink=True)
    sc.render.resolution_x, sc.render.resolution_y, sc.render.resolution_percentage = RW, RH, 100
    sc.render.film_transparent = True
    sc.render.image_settings.file_format = "PNG"
    sc.render.image_settings.color_mode = "RGBA"
    sc.render.image_settings.color_depth = "16"
    try:
        sc.view_settings.view_transform = "Standard"
    except TypeError:
        pass
    sc.view_settings.look = "None" if "None" in [i.identifier for i in sc.view_settings.bl_rna.properties["look"].enum_items] else sc.view_settings.look
    engines = [i.identifier for i in sc.render.bl_rna.properties["engine"].enum_items]
    sc.render.engine = "BLENDER_EEVEE" if "BLENDER_EEVEE" in engines else engines[0]
    try:
        sc.eevee.taa_render_samples = 64
    except AttributeError:
        pass
    cam = bpy.data.cameras.new("cam")
    cam.type = "ORTHO"
    cam.ortho_scale = LX
    cam.clip_start, cam.clip_end = 0.1, 200
    co = bpy.data.objects.new("cam", cam)
    sc.collection.objects.link(co)
    co.location = (0.0, 0.0, 40.0)
    co.rotation_euler = (0.0, 0.0, 0.0)           # looking down -Z at the XY plane
    sc.camera = co
    return sc


def read_pixels(img):
    import numpy as np
    w, h = img.size
    a = np.array(img.pixels[:], dtype=np.float32).reshape(h, w, 4)
    return a[::-1]                                  # Blender stores bottom-up -> flip to top-down


def blur_wrap(a, rad_x, rad_y):
    """Separable box-ish blur with WRAP-AROUND in x (keeps seamless tiling) and clamp in y."""
    import numpy as np
    def box(arr, r, axis, wrap):
        if r <= 0:
            return arr
        k = 2 * r + 1
        acc = np.zeros_like(arr)
        for d in range(-r, r + 1):
            acc += np.roll(arr, d, axis=axis) if wrap else np.take(arr, np.clip(np.arange(arr.shape[axis]) + d, 0, arr.shape[axis] - 1), axis=axis)
        return acc / k
    return box(box(a, rad_x, 1, True), rad_y, 0, False)


def bake_layer(sc, lid, p):
    import numpy as np
    ob = build_ribbon(p, "ribbon_" + lid)
    ob.data.materials.append(shader_material())
    out_png = os.path.join(OUT, "_r_%s.png" % lid)
    sc.render.filepath = out_png
    bpy.ops.render.render(write_still=True)
    img = bpy.data.images.load(out_png)
    px = read_pixels(img)                           # RH x RW x 4 (rgb premult-ish, a coverage)
    bpy.data.images.remove(img)
    lum = px[..., 0]
    alpha = px[..., 3]
    # un-premultiply intensity where covered
    inten = np.where(alpha > 1e-4, lum / np.maximum(alpha, 1e-4), 0.0)
    # soft edges: blur the coverage a little (wrap in x), then box-downsample SSxSS
    alpha = blur_wrap(alpha, SS * 2, SS * 2)
    inten = blur_wrap(inten * (alpha > 0), SS, SS)
    def down(a):
        return a.reshape(H_OUT, SS, W_OUT, SS).mean(axis=(1, 3))
    A = np.clip(down(alpha), 0, 1)
    L = np.clip(down(inten), 0, 1)
    # gentle vertical fade near the frame edges so ribbons never cut off harshly
    yy = np.linspace(0, 1, H_OUT)[:, None]
    fade = np.clip(np.minimum(yy, 1 - yy) / 0.10, 0, 1) ** 1.2
    A = A * fade
    la = np.stack([(L * 255 + 0.5).astype(np.uint8), (A * 255 + 0.5).astype(np.uint8)], axis=-1)
    la.tofile(os.path.join(OUT, "ribbon_%s.la8" % lid))
    # RGBA preview (white-tinted) for eyeballing
    prev = bpy.data.images.new("prev_" + lid, W_OUT, H_OUT, alpha=True)
    flat = np.zeros((H_OUT, W_OUT, 4), dtype=np.float32)
    flat[..., 0] = flat[..., 1] = flat[..., 2] = L
    flat[..., 3] = A
    prev.pixels = flat[::-1].reshape(-1).tolist()
    prev.filepath_raw = os.path.join(OUT, "ribbon_%s.png" % lid)
    prev.file_format = "PNG"
    prev.save()
    bpy.data.images.remove(prev)
    os.remove(out_png)
    bpy.data.objects.remove(ob, do_unlink=True)
    seam = float(abs(la[:, 0, :].astype(int) - la[:, -1, :].astype(int)).mean())
    print("RIBBON %s: coverage=%.1f%% mean_L=%.0f seam_diff=%.2f" % (lid, A.mean() * 100, L[A > 0.05].mean() * 255 if (A > 0.05).any() else 0, seam))


def main():
    sc = setup_scene()
    for lid, p in LAYERS.items():
        bake_layer(sc, lid, p)
    print("MERIDIAN-RIBBONS: done ->", OUT)


main()
