/* ============================================================================
 * ide_templates.h -- in-source manifest of the Semantic LEGO IDE starter
 *                    templates (the "+ NEW" gallery), for AutomationOS.
 *
 * Each template is a COMPLETE, self-contained C program that BUILDS AND RUNS
 * with the on-device compiler (userspace/apps/ide/cc_*.c + tc_driver.c). The
 * canonical source for each lives beside this header as a plain file:
 *
 *     userspace/apps/ide/templates/NN_name.c
 *
 * and the exact bytes of each are embedded below as a C string literal in the
 * IDE_TEMPLATES[] array, so the IDE can offer them WITHOUT the files having to
 * be present on disk at run time.
 *
 * ---------------------------------------------------------------------------
 * THE on-device-cc SUBSET THESE TEMPLATES STAY INSIDE (why they look the way
 * they do -- every template obeys all of this, verified empirically):
 *   - NO preprocessor: #include / #define are not expanded. Templates are
 *     fully self-contained; the only "declarations" are prototypes for the
 *     builtins (sys_write / syscall), which the cc ignores and host gcc needs.
 *   - NO usable arrays (local OR global): a declared array yields only 8 bytes
 *     and indexing it loads the slot contents as a pointer -- it is broken.
 *     Mutable indexed data is modelled with scalar globals + bitmasks + if/else
 *     accessor ladders; READ-ONLY indexed data uses a char* walking a string
 *     literal (the one safe "array").
 *   - GLOBALS START AT ZERO: initializers on globals are dropped, so every
 *     global is assigned at run time (never "= value" at its declaration).
 *   - STRING LITERALS work; escapes \n \t \r \0 backslash dquote squote too.
 *   - Operators: + - * / % & | ^ << >> ! ~ unary +/- && || == != < <= > >=
 *     = and the compound forms, ++ -- (pre/post), ?:, comma, sizeof, casts.
 *   - Control flow: if/else, while, for, break, continue, return. NO switch,
 *     NO do-while, NO goto.
 *   - Functions: <= 6 params, recursion ok, simple-named calls only.
 *   - Builtins: sys_write(fd,buf,len), sys_exit(code), and the generic
 *     syscall(n,a1,a2,a3) -> n in rax, a1..a3 in rdi/rsi/rdx, result in rax.
 *   - main() takes no argc/argv; its return value is the process exit code.
 *   - NO stdin is proven for a terminal-spawned program, so every template
 *     uses hard-coded / scripted inputs and says so in its own banner.
 *
 * ---------------------------------------------------------------------------
 * INTEGRATION HINT -- how to wire these into the IDE "+ NEW" flow:
 *
 *   The existing gallery is DISK-DIRECTORY based. The "+ NEW" button (label
 *   NP_BTN_LABEL "+ NEW", ide.c) calls:
 *        void ide_new_project(Ide* a);     // ide.c (~line 853)
 *   which runs np_open() (ide.c ~824) -> ide_list_dir(IDE_TEMPLATES_DIR, ...).
 *   IDE_TEMPLATES_DIR is "/usr/src/templates" (ide.h:76). Each template is a
 *   sub-DIRECTORY there; picking one calls np_clone() (ide.c ~868), which copies
 *   the directory main .c into the new project src/main.c.
 *
 *   Two ways to surface THESE templates (pick one in the main session):
 *
 *   (A) Build-time staging (simplest, matches today mechanism):
 *       In scripts/build_all.sh, beside the existing template-staging block
 *       (the "IDE New Project templates -> /usr/src/templates" lines, ~695),
 *       add for each NN_name:
 *           mkdir -p /tmp/ird/usr/src/templates/NN_name
 *           cp userspace/apps/ide/templates/NN_name.c \
 *              /tmp/ird/usr/src/templates/NN_name/main.c
 *       np_clone() already prefers a file named main.c, so each shows up in the
 *       picker with no IDE code change.
 *
 *   (B) Built-in seeding from THIS header (no initrd dependency):
 *       Have the IDE, on first run, write each IDE_TEMPLATES[i].body to
 *           /usr/src/templates/<name>/main.c
 *       via ide_write_file (see ide_project_seed_main in ide_project.c:111 for
 *       the exact write idiom) before np_open() enumerates the directory. The
 *       .name field is the directory name; .title / .desc feed a richer picker
 *       label if the modal renderer is extended to show them.
 *
 *   Touch only ide.c / scripts when wiring; this header + templates/ are data.
 * ==========================================================================*/
#ifndef IDE_TEMPLATES_H
#define IDE_TEMPLATES_H

/* One starter template. `body` is the exact, on-device-buildable C source. */
typedef struct {
    const char* name;    /* directory / id, e.g. "01_login"        */
    const char* title;   /* short human label, e.g. "Login / Auth" */
    const char* desc;    /* one-line description for a picker       */
    const char* body;    /* the full C source (embedded verbatim)   */
} IdeTemplate;

static const IdeTemplate IDE_TEMPLATES[] = {
    {
        "01_login", "Login / Auth",
        "Password hashing (djb2), a fixed user table, and attempt lockout.",
        /* body (verbatim source of templates/01_login.c): */
        "/* ============================================================================\n"
        " * 01_login.c -- a login / authentication demo for the AutomationOS on-device C\n"
        " *               compiler (the \"cc\" the Semantic LEGO IDE builds with).\n"
        " *\n"
        " * WHAT THIS PROGRAM DOES (in words, for a reader who does not picture code):\n"
        " *   It pretends to be the front door of a system. There is a tiny fixed table\n"
        " *   of known users, each with a secret password. A short, hard-coded SCRIPT of\n"
        " *   login attempts is replayed. For each attempt we hash the typed password and\n"
        " *   compare it to the stored hash for that user. We count failures; after three\n"
        " *   failures the account is LOCKED and further attempts are refused even if the\n"
        " *   password becomes correct. Everything is printed, line by line, so you can\n"
        " *   read the whole story top to bottom.\n"
        " *\n"
        " * WHY THE STYLE IS UNUSUAL (the compiler's rules you must respect):\n"
        " *   The on-device cc is a small single-file C subset. The things it CANNOT do\n"
        " *   shaped every choice below:\n"
        " *     - NO #include / NO #define   : this file is fully self-contained.\n"
        " *     - NO usable arrays           : a declared array gives you only 8 bytes and\n"
        " *                                    indexing it is broken, so we DO NOT store a\n"
        " *                                    \"struct User table[N]\". Instead the table is\n"
        " *                                    expressed as code: a function that maps a\n"
        " *                                    user name to that user's stored password\n"
        " *                                    hash. This is the table -- just written as a\n"
        " *                                    decision tree instead of an array of rows.\n"
        " *     - GLOBALS START AT ZERO       : an initializer on a global is ignored, so\n"
        " *                                    every global is set at run time, never with\n"
        " *                                    \"= value\" at the declaration.\n"
        " *     - STRING LITERALS are fine    : they live in read-only data and you may\n"
        " *                                    walk them through a char* with s[i].\n"
        " *     - NO stdin is proven for a    : so the login attempts are HARD-CODED below.\n"
        " *       terminal-spawned program      A real interactive version would read the\n"
        " *                                      user name + password from the keyboard.\n"
        " *\n"
        " * HOW TO EXTEND IT:\n"
        " *   - Add a user: add one more \"if (streq(user, \\\"name\\\")) return hash(\\\"pw\\\");\"\n"
        " *     line inside pass_hash_for(). That is literally adding a row to the table.\n"
        " *   - Change the lockout threshold: edit LOCKOUT_AT in main().\n"
        " *   - Make it interactive: replace the scripted attempt(...) calls in main with\n"
        " *     reads of real input once a proven stdin path exists.\n"
        " *\n"
        " * The toolchain provides _start: it calls main() and turns main's return value\n"
        " * into the process exit code. We return the number of failed attempts.\n"
        " * ==========================================================================*/\n"
        "\n"
        "/* On-device builtins. The cc recognizes these names as direct syscalls; the\n"
        " * prototypes exist ONLY so a host \"gcc -fsyntax-only\" check passes. The\n"
        " * on-device compiler ignores prototypes (it emits only function bodies). */\n"
        "void sys_write(int fd, char *buf, int len);\n"
        "\n"
        "/* ---- tiny output layer (one byte at a time through a 1-byte global) -------\n"
        " * g_ch is the single mutable byte the writer points the kernel at. Pointing at\n"
        " * &g_ch sidesteps the subset's lack of real arrays. */\n"
        "char g_ch;\n"
        "\n"
        "/* emit: write one character to standard output (fd 1). */\n"
        "void emit(int c) { g_ch = c; sys_write(1, &g_ch, 1); }\n"
        "\n"
        "/* puts0: write a NUL-terminated C string by first measuring its length. */\n"
        "void puts0(char *s) {\n"
        "    int n = 0;\n"
        "    while (s[n]) n = n + 1;\n"
        "    sys_write(1, s, n);\n"
        "}\n"
        "\n"
        "/* putu: print a non-negative integer in decimal using recursion (no buffer). */\n"
        "void putu(int v) {\n"
        "    if (v >= 10) putu(v / 10);\n"
        "    emit('0' + v % 10);\n"
        "}\n"
        "\n"
        "/* puti: print a signed integer (handles the leading minus, then the digits). */\n"
        "void puti(int v) {\n"
        "    if (v < 0) { emit('-'); v = 0 - v; }\n"
        "    putu(v);\n"
        "}\n"
        "\n"
        "/* ---- string + hash primitives -------------------------------------------- */\n"
        "\n"
        "/* streq: return 1 if the two NUL-terminated strings are exactly equal, else 0. */\n"
        "int streq(char *a, char *b) {\n"
        "    int i = 0;\n"
        "    while (a[i] && b[i]) {\n"
        "        if (a[i] != b[i]) return 0;\n"
        "        i = i + 1;\n"
        "    }\n"
        "    return a[i] == b[i];          /* both ended together => equal */\n"
        "}\n"
        "\n"
        "/* hash: the classic djb2 string hash, written out so nothing is hidden.\n"
        " *   start at 5381; for each byte:  h = h*33 + byte.  (h*33 == (h<<5)+h)\n"
        " * Returns a 32-bit-ish integer fingerprint of the string. */\n"
        "int hash(char *s) {\n"
        "    int h = 5381;\n"
        "    int i = 0;\n"
        "    while (s[i]) {\n"
        "        h = ((h << 5) + h) + s[i];\n"
        "        i = i + 1;\n"
        "    }\n"
        "    return h;\n"
        "}\n"
        "\n"
        "/* ---- the \"user table\", expressed as a function ---------------------------\n"
        " * pass_hash_for: given a user name, return the stored hash of that user's\n"
        " * password, or 0 if the user is unknown. Storing the HASH (not the password)\n"
        " * is how real systems avoid keeping plaintext secrets. Each \"if\" line is one\n"
        " * row of the table. */\n"
        "int pass_hash_for(char *user) {\n"
        "    if (streq(user, \"alice\")) return hash(\"wonderland\");\n"
        "    if (streq(user, \"bob\"))   return hash(\"builder\");\n"
        "    if (streq(user, \"root\"))  return hash(\"toor\");\n"
        "    return 0;                     /* unknown user */\n"
        "}\n"
        "\n"
        "/* ---- the failure / lockout counter --------------------------------------- */\n"
        "int g_fail;                       /* number of failed attempts so far (set to 0 in main) */\n"
        "\n"
        "/* try_login: return 1 if (user,pass) is a valid pair, else 0. Unknown users\n"
        " * always fail. This does NOT touch the lockout counter -- that is policy, kept\n"
        " * in attempt() so this function stays a pure check. */\n"
        "int try_login(char *user, char *pass) {\n"
        "    int expected = pass_hash_for(user);\n"
        "    if (expected == 0) return 0;          /* no such user */\n"
        "    return hash(pass) == expected;        /* compare fingerprints */\n"
        "}\n"
        "\n"
        "/* attempt: run ONE scripted login attempt with the lockout policy applied.\n"
        " * Prints the outcome. Returns 1 if the user is now logged in, else 0. */\n"
        "int attempt(char *user, char *pass, int lockout_at) {\n"
        "    puts0(\"login: user='\");\n"
        "    puts0(user);\n"
        "    puts0(\"' ... \");\n"
        "\n"
        "    if (g_fail >= lockout_at) {            /* policy: refuse once locked */\n"
        "        puts0(\"ACCOUNT LOCKED (too many failures)\\n\");\n"
        "        return 0;\n"
        "    }\n"
        "    if (try_login(user, pass)) {\n"
        "        puts0(\"ACCESS GRANTED -- welcome, \");\n"
        "        puts0(user);\n"
        "        emit('\\n');\n"
        "        return 1;\n"
        "    }\n"
        "    g_fail = g_fail + 1;                    /* record the failure */\n"
        "    puts0(\"ACCESS DENIED (failures=\");\n"
        "    putu(g_fail);\n"
        "    puts0(\")\\n\");\n"
        "    return 0;\n"
        "}\n"
        "\n"
        "/* main: replay a fixed script of attempts that demonstrates success, repeated\n"
        " * failure, and lockout. Returns the number of failed attempts as the exit code.\n"
        " *\n"
        " * The main sequence, numbered:\n"
        " *   1. set the failure counter to 0 (globals start at 0, but we are explicit).\n"
        " *   2. a CORRECT login for 'alice'                  -> granted.\n"
        " *   3..5. three WRONG passwords for 'bob'           -> denied, denied, locked.\n"
        " *   6. the CORRECT password for 'bob' AFTER lockout -> still refused.\n"
        " *   7. print a summary line.\n"
        " */\n"
        "int main(void) {\n"
        "    int lockout_at = 3;\n"
        "\n"
        "    /* step 1 */\n"
        "    g_fail = 0;\n"
        "    puts0(\"== AutomationOS login demo ==\\n\");\n"
        "    puts0(\"known users: alice, bob, root (lockout after \");\n"
        "    putu(lockout_at);\n"
        "    puts0(\" failures)\\n\\n\");\n"
        "\n"
        "    /* step 2 */\n"
        "    attempt(\"alice\", \"wonderland\", lockout_at);\n"
        "\n"
        "    /* steps 3..5 */\n"
        "    attempt(\"bob\", \"hunter2\",   lockout_at);\n"
        "    attempt(\"bob\", \"password1\", lockout_at);\n"
        "    attempt(\"bob\", \"letmein\",   lockout_at);\n"
        "\n"
        "    /* step 6: correct now, but the account is already locked */\n"
        "    attempt(\"bob\", \"builder\",   lockout_at);\n"
        "\n"
        "    /* step 7 */\n"
        "    puts0(\"\\nsummary: \");\n"
        "    putu(g_fail);\n"
        "    puts0(\" failed attempt(s).\\n\");\n"
        "    return g_fail;\n"
        "}\n"
    },
    {
        "02_todo", "To-Do List",
        "Add / done / list over a bitmask-backed task set with fixed titles.",
        /* body (verbatim source of templates/02_todo.c): */
        "/* ============================================================================\n"
        " * 02_todo.c -- an in-memory to-do list driven by a scripted command sequence,\n"
        " *              for the AutomationOS on-device C compiler.\n"
        " *\n"
        " * WHAT THIS PROGRAM DOES (in words):\n"
        " *   There is a fixed CATALOG of eight possible task titles (slot 0..7). The list\n"
        " *   has two pieces of state, and that is ALL the state there is:\n"
        " *     - which slots are currently ON the list   (the \"active\" set)\n"
        " *     - which slots are marked DONE             (the \"done\" set)\n"
        " *   A short, hard-coded script of commands -- add, done, list -- is replayed,\n"
        " *   and after the interesting commands we print the whole list so you can watch\n"
        " *   it change.\n"
        " *\n"
        " * THE KEY IDEA -- A SET STORED AS THE BITS OF ONE INTEGER:\n"
        " *   The on-device cc has no usable arrays, so we cannot keep an array of task\n"
        " *   structs. Instead each task is a SLOT NUMBER 0..7, and a set of slots is\n"
        " *   stored as the bits of a single int:\n"
        " *       bit i == 1  means  \"slot i is in the set\".\n"
        " *   Adding slot i to a set:        set = set | (1 << i)\n"
        " *   Testing whether i is in a set: (set >> i) & 1\n"
        " *   This is the same trick a real kernel uses for small fixed collections, and\n"
        " *   it fits the compiler's scalar-only world perfectly. g_active holds the\n"
        " *   \"on the list\" set; g_done holds the \"completed\" set. The titles themselves\n"
        " *   are string literals returned by title(i) -- read-only, which is why we can\n"
        " *   keep them even without writable arrays.\n"
        " *\n"
        " * COMPILER RULES THAT SHAPED THIS FILE:\n"
        " *   - NO #include / #define; self-contained.\n"
        " *   - GLOBALS START AT ZERO and initializers are ignored -> we set g_active and\n"
        " *     g_done to 0 explicitly in main.\n"
        " *   - NO stdin is proven for a terminal-spawned program -> the commands are a\n"
        " *     fixed script. A real version would parse typed commands instead.\n"
        " *\n"
        " * HOW TO EXTEND IT:\n"
        " *   - More tasks: extend title() with more \"if (i == N) return \\\"...\\\";\" lines\n"
        " *     (you have room up to bit 30 in an int; keep titles read-only literals).\n"
        " *   - New command: write a function that edits g_active / g_done with the bit\n"
        " *     operations above, then call it from main's script.\n"
        " *\n"
        " * Exit code = number of completed tasks at the end.\n"
        " * ==========================================================================*/\n"
        "\n"
        "/* On-device builtin (prototype only for the host syntax check; see 01_login.c). */\n"
        "void sys_write(int fd, char *buf, int len);\n"
        "\n"
        "/* ---- output layer --------------------------------------------------------- */\n"
        "char g_ch;\n"
        "/* emit: write a single character to stdout. */\n"
        "void emit(int c) { g_ch = c; sys_write(1, &g_ch, 1); }\n"
        "/* puts0: write a NUL-terminated string. */\n"
        "void puts0(char *s) { int n = 0; while (s[n]) n = n + 1; sys_write(1, s, n); }\n"
        "/* putu: print a non-negative integer in decimal (recursive, no buffer). */\n"
        "void putu(int v) { if (v >= 10) putu(v / 10); emit('0' + v % 10); }\n"
        "\n"
        "/* ---- the fixed title catalog --------------------------------------------\n"
        " * title: return the read-only title text for slot i (0..7), or a placeholder. */\n"
        "char *title(int i) {\n"
        "    if (i == 0) return \"water the plants\";\n"
        "    if (i == 1) return \"write the design doc\";\n"
        "    if (i == 2) return \"review pull request\";\n"
        "    if (i == 3) return \"back up the disk image\";\n"
        "    if (i == 4) return \"answer email\";\n"
        "    if (i == 5) return \"refactor the parser\";\n"
        "    if (i == 6) return \"call the dentist\";\n"
        "    if (i == 7) return \"ship the release\";\n"
        "    return \"(empty slot)\";\n"
        "}\n"
        "\n"
        "/* ---- the two sets, each stored as the bits of one int -------------------- */\n"
        "int g_active;     /* bit i set => task i is on the list   (set to 0 in main) */\n"
        "int g_done;       /* bit i set => task i is completed      (set to 0 in main) */\n"
        "\n"
        "/* is_active: 1 if slot i is currently on the list, else 0. */\n"
        "int is_active(int i) { return (g_active >> i) & 1; }\n"
        "/* is_done: 1 if slot i is marked completed, else 0. */\n"
        "int is_done(int i)   { return (g_done >> i) & 1; }\n"
        "\n"
        "/* add_task: put slot i on the list (idempotent). Prints what it did. */\n"
        "void add_task(int i) {\n"
        "    g_active = g_active | (1 << i);\n"
        "    puts0(\"  + added: \");\n"
        "    puts0(title(i));\n"
        "    emit('\\n');\n"
        "}\n"
        "\n"
        "/* complete_task: mark slot i done IF it is on the list. Prints the outcome. */\n"
        "void complete_task(int i) {\n"
        "    if (!is_active(i)) {\n"
        "        puts0(\"  ! cannot complete slot \");\n"
        "        putu(i);\n"
        "        puts0(\" -- not on the list\\n\");\n"
        "        return;\n"
        "    }\n"
        "    g_done = g_done | (1 << i);\n"
        "    puts0(\"  * done: \");\n"
        "    puts0(title(i));\n"
        "    emit('\\n');\n"
        "}\n"
        "\n"
        "/* count_done: return how many slots are both active and done. */\n"
        "int count_done(void) {\n"
        "    int i = 0;\n"
        "    int n = 0;\n"
        "    while (i < 8) {\n"
        "        if (is_active(i) && is_done(i)) n = n + 1;\n"
        "        i = i + 1;\n"
        "    }\n"
        "    return n;\n"
        "}\n"
        "\n"
        "/* list_tasks: print every active task with a [x] (done) or [ ] (todo) box. */\n"
        "void list_tasks(void) {\n"
        "    int i = 0;\n"
        "    int shown = 0;\n"
        "    puts0(\"  --- current list ---\\n\");\n"
        "    while (i < 8) {\n"
        "        if (is_active(i)) {\n"
        "            if (is_done(i)) puts0(\"  [x] \");\n"
        "            else            puts0(\"  [ ] \");\n"
        "            puts0(title(i));\n"
        "            emit('\\n');\n"
        "            shown = shown + 1;\n"
        "        }\n"
        "        i = i + 1;\n"
        "    }\n"
        "    if (shown == 0) puts0(\"  (the list is empty)\\n\");\n"
        "}\n"
        "\n"
        "/* main: replay a fixed script of commands and watch the list evolve.\n"
        " * The sequence, numbered:\n"
        " *   1. zero both sets (globals start at 0; we are explicit for clarity).\n"
        " *   2. add tasks 0, 1, 2.\n"
        " *   3. list.\n"
        " *   4. complete task 1.\n"
        " *   5. try to complete task 5 (not on the list -> refused).\n"
        " *   6. add task 3; complete task 0.\n"
        " *   7. final list + a count summary.\n"
        " */\n"
        "int main(void) {\n"
        "    /* step 1 */\n"
        "    g_active = 0;\n"
        "    g_done   = 0;\n"
        "    puts0(\"== AutomationOS to-do demo ==\\n\\n\");\n"
        "\n"
        "    /* step 2 */\n"
        "    puts0(\"command: add 0,1,2\\n\");\n"
        "    add_task(0);\n"
        "    add_task(1);\n"
        "    add_task(2);\n"
        "\n"
        "    /* step 3 */\n"
        "    puts0(\"command: list\\n\");\n"
        "    list_tasks();\n"
        "\n"
        "    /* step 4 */\n"
        "    puts0(\"command: done 1\\n\");\n"
        "    complete_task(1);\n"
        "\n"
        "    /* step 5 */\n"
        "    puts0(\"command: done 5\\n\");\n"
        "    complete_task(5);\n"
        "\n"
        "    /* step 6 */\n"
        "    puts0(\"command: add 3; done 0\\n\");\n"
        "    add_task(3);\n"
        "    complete_task(0);\n"
        "\n"
        "    /* step 7 */\n"
        "    puts0(\"command: list\\n\");\n"
        "    list_tasks();\n"
        "    puts0(\"\\nsummary: \");\n"
        "    putu(count_done());\n"
        "    puts0(\" task(s) completed.\\n\");\n"
        "    return count_done();\n"
        "}\n"
    },
    {
        "03_guess", "Number Guessing",
        "A deterministic LCG pseudo-random generator vs a binary-search self-player.",
        /* body (verbatim source of templates/03_guess.c): */
        "/* ============================================================================\n"
        " * 03_guess.c -- a number-guessing game against a deterministic pseudo-random\n"
        " *               number generator, played automatically by a self-play driver,\n"
        " *               for the AutomationOS on-device C compiler.\n"
        " *\n"
        " * WHAT THIS PROGRAM DOES (in words):\n"
        " *   The computer \"thinks of\" a secret number from 0 to 99. Then a SELF-PLAYER\n"
        " *   tries to find it using binary search: it keeps a low bound and a high bound,\n"
        " *   always guesses the middle, and after each guess it learns \"too low\" or\n"
        " *   \"too high\" and shrinks the range by half. Every guess and hint is printed,\n"
        " *   and the search is guaranteed to finish in at most 7 guesses (because\n"
        " *   halving 100 possibilities reaches 1 in 7 steps).\n"
        " *\n"
        " * WHERE THE SECRET COMES FROM -- A LINEAR CONGRUENTIAL GENERATOR (LCG):\n"
        " *   There is no hardware randomness here and we want the run to be repeatable,\n"
        " *   so we use an LCG, the simplest classic pseudo-random generator, written out\n"
        " *   in full:\n"
        " *       state = state * 1103515245 + 12345        (the glibc constants)\n"
        " *       output = (state >> 16) & 32767            (take some high bits, keep them positive)\n"
        " *   Feeding the same SEED always produces the same sequence -- that determinism\n"
        " *   is a feature here, so the demo behaves the same every time. The secret is\n"
        " *   simply the first output, taken modulo 100.\n"
        " *\n"
        " * COMPILER RULES THAT SHAPED THIS FILE:\n"
        " *   - NO #include / #define; self-contained, integers only (the cc has no FPU).\n"
        " *   - GLOBALS START AT ZERO and initializers are ignored -> the LCG state is\n"
        " *     seeded at run time inside main, never with \"= seed\" at the declaration.\n"
        " *   - NO stdin needed: this is a zero-player game; the driver plays itself.\n"
        " *\n"
        " * HOW TO EXTEND IT:\n"
        " *   - Change the secret: edit the SEED in main, or the \"% 100\" range.\n"
        " *   - Make it interactive: replace the self-play loop's computed guess with a\n"
        " *     real keyboard read once a proven stdin path exists; the hint logic is the\n"
        " *     same.\n"
        " *\n"
        " * Exit code = the number of guesses the self-player needed.\n"
        " * ==========================================================================*/\n"
        "\n"
        "/* On-device builtin (prototype only for the host syntax check; see 01_login.c). */\n"
        "void sys_write(int fd, char *buf, int len);\n"
        "\n"
        "/* ---- output layer --------------------------------------------------------- */\n"
        "char g_ch;\n"
        "/* emit: write a single character to stdout. */\n"
        "void emit(int c) { g_ch = c; sys_write(1, &g_ch, 1); }\n"
        "/* puts0: write a NUL-terminated string. */\n"
        "void puts0(char *s) { int n = 0; while (s[n]) n = n + 1; sys_write(1, s, n); }\n"
        "/* putu: print a non-negative integer in decimal (recursive). */\n"
        "void putu(int v) { if (v >= 10) putu(v / 10); emit('0' + v % 10); }\n"
        "\n"
        "/* ---- the pseudo-random generator ----------------------------------------- */\n"
        "int g_rng;        /* the LCG state (seeded in main; globals start at 0) */\n"
        "\n"
        "/* rng_next: advance the LCG and return a non-negative pseudo-random int.\n"
        " *   Contract: deterministic for a given starting g_rng; result is 0..32767. */\n"
        "int rng_next(void) {\n"
        "    g_rng = g_rng * 1103515245 + 12345;   /* the LCG recurrence (wraps; fine) */\n"
        "    return (g_rng >> 16) & 32767;          /* high bits, masked positive */\n"
        "}\n"
        "\n"
        "/* pick_secret: choose the secret number in [0, 99] from the next LCG output. */\n"
        "int pick_secret(void) {\n"
        "    return rng_next() % 100;\n"
        "}\n"
        "\n"
        "/* main: seed the generator, pick a secret, and let the binary-search self-player\n"
        " * find it. Returns the guess count.\n"
        " *\n"
        " * The self-play loop, numbered:\n"
        " *   1. seed the LCG and choose the secret (kept hidden from the search logic).\n"
        " *   2. set lo = 0, hi = 99, tries = 0.\n"
        " *   3. while lo <= hi and we are under the safety cap:\n"
        " *        a. guess = the midpoint (lo + hi) / 2; count the try; print it.\n"
        " *        b. if guess == secret  -> announce success and stop.\n"
        " *        c. if guess <  secret  -> print \"too low\",  raise lo to guess + 1.\n"
        " *        d. else                -> print \"too high\", lower hi to guess - 1.\n"
        " *   4. print how many guesses it took.\n"
        " */\n"
        "int main(void) {\n"
        "    int lo;\n"
        "    int hi;\n"
        "    int tries;\n"
        "    int secret;\n"
        "    int guess;\n"
        "\n"
        "    /* step 1 */\n"
        "    g_rng = 20260610;                 /* the SEED: change it for a different secret */\n"
        "    secret = pick_secret();\n"
        "    puts0(\"== AutomationOS guessing game (self-play) ==\\n\");\n"
        "    puts0(\"the computer picked a secret in 0..99; binary search will find it.\\n\\n\");\n"
        "\n"
        "    /* step 2 */\n"
        "    lo = 0;\n"
        "    hi = 99;\n"
        "    tries = 0;\n"
        "\n"
        "    /* step 3 */\n"
        "    while (lo <= hi && tries < 16) {\n"
        "        guess = (lo + hi) / 2;        /* a */\n"
        "        tries = tries + 1;\n"
        "        puts0(\"guess #\");\n"
        "        putu(tries);\n"
        "        puts0(\" -> \");\n"
        "        putu(guess);\n"
        "        puts0(\" : \");\n"
        "\n"
        "        if (guess == secret) {        /* b */\n"
        "            puts0(\"correct!\\n\");\n"
        "            lo = hi + 1;              /* force the loop to end */\n"
        "        } else if (guess < secret) {  /* c */\n"
        "            puts0(\"too low\\n\");\n"
        "            lo = guess + 1;\n"
        "        } else {                      /* d */\n"
        "            puts0(\"too high\\n\");\n"
        "            hi = guess - 1;\n"
        "        }\n"
        "    }\n"
        "\n"
        "    /* step 4 */\n"
        "    puts0(\"\\nfound \");\n"
        "    putu(secret);\n"
        "    puts0(\" in \");\n"
        "    putu(tries);\n"
        "    puts0(\" guess(es).\\n\");\n"
        "    return tries;\n"
        "}\n"
    },
    {
        "04_clock", "Elapsed Clock",
        "Reads SYS_GET_TICKS_MS in a bounded loop and formats elapsed time as mm:ss.",
        /* body (verbatim source of templates/04_clock.c): */
        "/* ============================================================================\n"
        " * 04_clock.c -- read the kernel's millisecond clock, format elapsed time as\n"
        " *               mm:ss, print a few samples, then exit cleanly. For the\n"
        " *               AutomationOS on-device C compiler.\n"
        " *\n"
        " * WHAT THIS PROGRAM DOES (in words):\n"
        " *   It reads the kernel's monotonic millisecond counter once to get a START\n"
        " *   time. Then it loops a FIXED number of times (five). On each pass it sleeps\n"
        " *   a short, fixed amount, reads the clock again, subtracts the start to get the\n"
        " *   elapsed milliseconds, and prints that elapsed time as minutes:seconds plus\n"
        " *   the raw millisecond count. The loop is BOUNDED -- it runs exactly five times\n"
        " *   and then the program returns. There is no infinite loop anywhere; a clock\n"
        " *   you cannot escape would be a hung process, which is exactly what we avoid.\n"
        " *\n"
        " * HOW IT TALKS TO THE KERNEL -- THE GENERIC syscall() BUILTIN:\n"
        " *   The on-device cc exposes any kernel call through a builtin named syscall:\n"
        " *       syscall(number, arg1, arg2)   ->  number in rax, arg1 in rdi, arg2 in rsi\n"
        " *   and the kernel's result comes back as the return value. We use two numbers:\n"
        " *       40  = SYS_GET_TICKS_MS  : returns milliseconds since boot (no args)\n"
        " *        9  = SYS_SLEEP         : sleep for arg1 milliseconds\n"
        " *   These numbers come straight from kernel/include/syscall.h. No inline\n"
        " *   assembly and no libc are involved -- the compiler turns the syscall(...)\n"
        " *   call directly into a `syscall` instruction.\n"
        " *\n"
        " * COMPILER RULES THAT SHAPED THIS FILE:\n"
        " *   - NO #include / #define; self-contained, integers only.\n"
        " *   - GLOBALS START AT ZERO; we keep all state in locals here anyway.\n"
        " *   - The loop count is a literal constant, so the program always terminates.\n"
        " *\n"
        " * HOW TO EXTEND IT:\n"
        " *   - Sample more often / longer: change SAMPLES or the nap() argument in main.\n"
        " *   - Show a real wall clock: SYS_GET_TICKS_MS is \"since boot\"; add an offset if\n"
        " *     you later wire a real-time clock.\n"
        " *\n"
        " * Exit code = 0 (a clean finish).\n"
        " * ==========================================================================*/\n"
        "\n"
        "/* On-device builtins (prototypes only for the host syntax check; see 01_login.c).\n"
        " * sys_write is the SYS_WRITE convenience builtin; syscall is the generic one. */\n"
        "void sys_write(int fd, char *buf, int len);\n"
        "long syscall(long number, long arg1, long arg2);\n"
        "\n"
        "/* ---- output layer --------------------------------------------------------- */\n"
        "char g_ch;\n"
        "/* emit: write a single character to stdout. */\n"
        "void emit(int c) { g_ch = c; sys_write(1, &g_ch, 1); }\n"
        "/* puts0: write a NUL-terminated string. */\n"
        "void puts0(char *s) { int n = 0; while (s[n]) n = n + 1; sys_write(1, s, n); }\n"
        "/* putu: print a non-negative integer in decimal (recursive). */\n"
        "void putu(int v) { if (v >= 10) putu(v / 10); emit('0' + v % 10); }\n"
        "\n"
        "/* put2: print exactly two decimal digits with a leading zero (for mm and ss).\n"
        " *   Contract: v is 0..99; prints \"00\"..\"99\". */\n"
        "void put2(int v) {\n"
        "    emit('0' + (v / 10) % 10);\n"
        "    emit('0' + v % 10);\n"
        "}\n"
        "\n"
        "/* ---- kernel time helpers -------------------------------------------------- */\n"
        "\n"
        "/* ticks: milliseconds since boot, via SYS_GET_TICKS_MS (number 40). */\n"
        "int ticks(void) {\n"
        "    return (int)syscall(40, 0, 0);\n"
        "}\n"
        "\n"
        "/* nap: sleep for ms milliseconds, via SYS_SLEEP (number 9). The return value is\n"
        " * ignored; if the kernel cannot sleep it simply returns and the loop continues\n"
        " * (still bounded). */\n"
        "void nap(int ms) {\n"
        "    syscall(9, ms, 0);\n"
        "}\n"
        "\n"
        "/* main: sample the clock five times, printing elapsed mm:ss each pass.\n"
        " *\n"
        " * The loop, numbered:\n"
        " *   1. read t0 = the start time in milliseconds.\n"
        " *   2. print a header.\n"
        " *   3. for i = 1..SAMPLES:\n"
        " *        a. nap a fixed number of milliseconds.\n"
        " *        b. read the clock now; elapsed_ms = now - t0.\n"
        " *        c. total_seconds = elapsed_ms / 1000; mm = total/60; ss = total%60.\n"
        " *        d. print \"i)  mm:ss   (elapsed_ms ms)\".\n"
        " *   4. print a closing line and return 0.\n"
        " */\n"
        "int main(void) {\n"
        "    int SAMPLES = 5;\n"
        "    int t0;\n"
        "    int i;\n"
        "\n"
        "    /* step 1 */\n"
        "    t0 = ticks();\n"
        "\n"
        "    /* step 2 */\n"
        "    puts0(\"== AutomationOS clock demo ==\\n\");\n"
        "    puts0(\"reading SYS_GET_TICKS_MS; \");\n"
        "    putu(SAMPLES);\n"
        "    puts0(\" bounded samples.\\n\\n\");\n"
        "\n"
        "    /* step 3 */\n"
        "    i = 1;\n"
        "    while (i <= SAMPLES) {\n"
        "        int now;\n"
        "        int elapsed_ms;\n"
        "        int total_sec;\n"
        "        int mm;\n"
        "        int ss;\n"
        "\n"
        "        nap(250);                         /* a */\n"
        "        now = ticks();                    /* b */\n"
        "        elapsed_ms = now - t0;\n"
        "        if (elapsed_ms < 0) elapsed_ms = 0;   /* guard against counter quirks */\n"
        "        total_sec = elapsed_ms / 1000;    /* c */\n"
        "        mm = total_sec / 60;\n"
        "        ss = total_sec % 60;\n"
        "\n"
        "        putu(i);                          /* d */\n"
        "        puts0(\")  \");\n"
        "        put2(mm);\n"
        "        emit(':');\n"
        "        put2(ss);\n"
        "        puts0(\"   (\");\n"
        "        putu(elapsed_ms);\n"
        "        puts0(\" ms)\\n\");\n"
        "\n"
        "        i = i + 1;\n"
        "    }\n"
        "\n"
        "    /* step 4 */\n"
        "    puts0(\"\\ndone -- clock demo finished cleanly.\\n\");\n"
        "    return 0;\n"
        "}\n"
    },
    {
        "05_calc", "Expression Evaluator",
        "Recursive-descent integer + - * / with precedence and parentheses.",
        /* body (verbatim source of templates/05_calc.c): */
        "/* ============================================================================\n"
        " * 05_calc.c -- a tiny integer expression evaluator: + - * / with correct\n"
        " *              operator precedence and parentheses, parsed by RECURSIVE DESCENT\n"
        " *              over a string. For the AutomationOS on-device C compiler. This is\n"
        " *              the \"learn recursion\" template.\n"
        " *\n"
        " * WHAT THIS PROGRAM DOES (in words):\n"
        " *   It reads a small arithmetic expression written as text, such as \"2+3*4\" or\n"
        " *   \"(2+3)*4\", and computes its integer value the way you would expect: * and /\n"
        " *   bind tighter than + and -, and parentheses override everything. It prints\n"
        " *   each expression next to its result. A handful of expressions are evaluated\n"
        " *   to show it working.\n"
        " *\n"
        " * THE BIG IDEA -- A GRAMMAR MADE OF THREE FUNCTIONS THAT CALL EACH OTHER:\n"
        " *   Precedence is expressed by LAYERS, each a function, each handling one\n"
        " *   precedence level and deferring tighter-binding work to the next layer down:\n"
        " *\n"
        " *       expr   :=  term   { ('+' | '-') term }      <- lowest precedence\n"
        " *       term   :=  factor { ('*' | '/') factor }    <- higher precedence\n"
        " *       factor :=  number | '(' expr ')' | '-' factor   <- highest; recurses to expr\n"
        " *\n"
        " *   Reading top to bottom: an expression is a chain of terms added/subtracted; a\n"
        " *   term is a chain of factors multiplied/divided; a factor is a number, or a\n"
        " *   whole parenthesized expression (which is why factor calls expr again -- that\n"
        " *   call is the recursion that makes nesting work to any depth).\n"
        " *\n"
        " * HOW THE STRING IS READ -- A CURSOR, NOT AN ARRAY:\n"
        " *   The on-device cc has no writable arrays, but a STRING LITERAL is real\n"
        " *   read-only memory and a char* can walk it. So the \"input\" is two globals:\n"
        " *       g_src  : a char* pointing at the expression text\n"
        " *       g_pos  : how many characters we have consumed so far\n"
        " *   peek() looks at the current character (g_src[g_pos]); advance() moves the\n"
        " *   cursor forward by one. The terminating NUL of the string stops every loop,\n"
        " *   so we never read past the end.\n"
        " *\n"
        " * COMPILER RULES THAT SHAPED THIS FILE:\n"
        " *   - NO #include / #define; self-contained, integers only.\n"
        " *   - GLOBALS START AT ZERO; g_src and g_pos are set at the top of eval().\n"
        " *   - Forward prototypes are declared so the mutually-recursive functions can\n"
        " *     refer to each other (and so a host syntax check passes).\n"
        " *   - NO stdin needed: the expressions are string literals.\n"
        " *\n"
        " * HOW TO EXTEND IT:\n"
        " *   - Add '%' (modulo): handle it in parse_term beside '*' and '/'.\n"
        " *   - Add comparison or power: introduce a new precedence LAYER (another\n"
        " *     function) above or below the right level and chain it in.\n"
        " *   - Evaluate user input: point g_src at a typed string once a proven stdin\n"
        " *     path exists; the parser does not change.\n"
        " *\n"
        " * Exit code = 0.\n"
        " * ==========================================================================*/\n"
        "\n"
        "/* On-device builtin (prototype only for the host syntax check; see 01_login.c). */\n"
        "void sys_write(int fd, char *buf, int len);\n"
        "\n"
        "/* ---- output layer --------------------------------------------------------- */\n"
        "char g_ch;\n"
        "/* emit: write a single character to stdout. */\n"
        "void emit(int c) { g_ch = c; sys_write(1, &g_ch, 1); }\n"
        "/* puts0: write a NUL-terminated string. */\n"
        "void puts0(char *s) { int n = 0; while (s[n]) n = n + 1; sys_write(1, s, n); }\n"
        "/* puti: print a signed integer in decimal. */\n"
        "void putu(int v) { if (v >= 10) putu(v / 10); emit('0' + v % 10); }\n"
        "void puti(int v) { if (v < 0) { emit('-'); v = 0 - v; } putu(v); }\n"
        "\n"
        "/* ---- the input cursor ----------------------------------------------------- */\n"
        "char *g_src;      /* the expression text (set in eval) */\n"
        "int   g_pos;      /* index of the next unread character (set to 0 in eval) */\n"
        "\n"
        "/* peek: the current character, or 0 (NUL) at the end of the string. */\n"
        "int peek(void) { return g_src[g_pos]; }\n"
        "/* advance: consume the current character (move the cursor forward by one). */\n"
        "void advance(void) { g_pos = g_pos + 1; }\n"
        "/* skip_ws: consume any run of spaces so \" 2 + 3 \" parses like \"2+3\". */\n"
        "void skip_ws(void) { while (peek() == ' ') advance(); }\n"
        "\n"
        "/* Forward declarations: parse_factor needs to call parse_expr for parentheses,\n"
        " * but parse_expr is defined later. On-device these prototypes are ignored (the\n"
        " * call is resolved by name); on the host they let the file type-check. */\n"
        "int parse_expr(void);\n"
        "int parse_term(void);\n"
        "int parse_factor(void);\n"
        "\n"
        "/* parse_number: read a run of digits and return its value.\n"
        " *   Contract: the cursor is on a digit; on return it is just past the number. */\n"
        "int parse_number(void) {\n"
        "    int v = 0;\n"
        "    while (peek() >= '0' && peek() <= '9') {\n"
        "        v = v * 10 + (peek() - '0');\n"
        "        advance();\n"
        "    }\n"
        "    return v;\n"
        "}\n"
        "\n"
        "/* parse_factor: the highest-precedence layer.\n"
        " *   Handles: a parenthesized sub-expression, a unary minus, or a plain number.\n"
        " *   Contract: returns the factor's value; the cursor ends just past it. */\n"
        "int parse_factor(void) {\n"
        "    skip_ws();\n"
        "    if (peek() == '(') {\n"
        "        advance();                 /* consume '(' */\n"
        "        int v = parse_expr();      /* THE RECURSION: a full expression inside */\n"
        "        skip_ws();\n"
        "        if (peek() == ')') advance();   /* consume the matching ')' */\n"
        "        return v;\n"
        "    }\n"
        "    if (peek() == '-') {\n"
        "        advance();                 /* unary minus: negate the next factor */\n"
        "        return 0 - parse_factor();\n"
        "    }\n"
        "    return parse_number();\n"
        "}\n"
        "\n"
        "/* parse_term: the * and / layer. Start with one factor, then fold in each\n"
        " *   following '*' factor or '/' factor, left to right.\n"
        " *   Contract: returns the term's value; cursor ends just past it. */\n"
        "int parse_term(void) {\n"
        "    int v = parse_factor();\n"
        "    skip_ws();\n"
        "    while (peek() == '*' || peek() == '/') {\n"
        "        int op = peek();\n"
        "        advance();\n"
        "        int r = parse_factor();\n"
        "        if (op == '*') v = v * r;\n"
        "        else           v = v / r;\n"
        "        skip_ws();\n"
        "    }\n"
        "    return v;\n"
        "}\n"
        "\n"
        "/* parse_expr: the + and - layer (lowest precedence). Start with one term, then\n"
        " *   fold in each following '+' term or '-' term, left to right.\n"
        " *   Contract: returns the expression's value; cursor ends at NUL or ')'. */\n"
        "int parse_expr(void) {\n"
        "    int v = parse_term();\n"
        "    skip_ws();\n"
        "    while (peek() == '+' || peek() == '-') {\n"
        "        int op = peek();\n"
        "        advance();\n"
        "        int r = parse_term();\n"
        "        if (op == '+') v = v + r;\n"
        "        else           v = v - r;\n"
        "        skip_ws();\n"
        "    }\n"
        "    return v;\n"
        "}\n"
        "\n"
        "/* eval: point the cursor at s, reset the position, and evaluate the whole thing. */\n"
        "int eval(char *s) {\n"
        "    g_src = s;\n"
        "    g_pos = 0;\n"
        "    return parse_expr();\n"
        "}\n"
        "\n"
        "/* show: print \"<expr> = <value>\" on its own line. */\n"
        "void show(char *s) {\n"
        "    puts0(s);\n"
        "    puts0(\" = \");\n"
        "    puti(eval(s));\n"
        "    emit('\\n');\n"
        "}\n"
        "\n"
        "/* main: evaluate several expressions that together prove precedence, left-to-\n"
        " * right folding, parentheses, and unary minus all work.\n"
        " *   1. print a header.\n"
        " *   2. evaluate the sample expressions.\n"
        " *   3. return 0.\n"
        " */\n"
        "int main(void) {\n"
        "    /* step 1 */\n"
        "    puts0(\"== AutomationOS expression evaluator ==\\n\");\n"
        "    puts0(\"integer + - * / with precedence and parentheses\\n\\n\");\n"
        "\n"
        "    /* step 2 */\n"
        "    show(\"2+3*4\");          /* precedence: 2 + 12        = 14 */\n"
        "    show(\"(2+3)*4\");        /* parentheses: 5 * 4        = 20 */\n"
        "    show(\"100/5-7\");        /* left to right: 20 - 7     = 13 */\n"
        "    show(\"2*2*2*2*2\");      /* repeated multiply         = 32 */\n"
        "    show(\"10 - 2 - 3\");     /* left-assoc subtraction    =  5 */\n"
        "    show(\"-(4+1)*2\");       /* unary minus then multiply = -10 */\n"
        "    show(\"7 + 6 * (5 - 2)\");/* nested parens: 7 + 18     = 25 */\n"
        "\n"
        "    /* step 3 */\n"
        "    puts0(\"\\ndone.\\n\");\n"
        "    return 0;\n"
        "}\n"
    },
    {
        "06_kvstore", "Key/Value Store",
        "A fixed-slot set / get / has / delete with a PASS/FAIL self-test.",
        /* body (verbatim source of templates/06_kvstore.c): */
        "/* ============================================================================\n"
        " * 06_kvstore.c -- a fixed-slot key/value store with set / get / has / delete,\n"
        " *                 plus a self-test that prints PASS / FAIL lines. For the\n"
        " *                 AutomationOS on-device C compiler. This template teaches the\n"
        " *                 house \"prove it with a self-test\" style.\n"
        " *\n"
        " * WHAT THIS PROGRAM DOES (in words):\n"
        " *   It is a tiny dictionary that maps an integer KEY to an integer VALUE, with\n"
        " *   room for exactly FOUR entries. You can:\n"
        " *       set(key, value)  -- insert a new pair, or overwrite an existing key\n"
        " *       get(key)         -- fetch the value for a key (0 if absent)\n"
        " *       has(key)         -- ask whether a key is present (1 or 0)\n"
        " *       del(key)         -- remove a key\n"
        " *   After defining the store, a SELF-TEST runs a sequence of operations whose\n"
        " *   answers are known in advance, and prints \"PASS <name>\" or \"FAIL <name>\" for\n"
        " *   each check. The program's exit code is the number of FAILED checks, so a\n"
        " *   clean run exits with 0 -- the same convention the OS test suite uses.\n"
        " *\n"
        " * HOW THE STORE IS BUILT WITHOUT ARRAYS:\n"
        " *   The on-device cc has no usable arrays, so the four slots are eight plain\n"
        " *   integer globals -- k0..k3 for the keys and v0..v3 for the values -- plus one\n"
        " *   integer g_used whose bit i means \"slot i currently holds a pair\". Because we\n"
        " *   cannot write \"slots[i]\", we reach a slot through ACCESSOR functions that map\n"
        " *   an index 0..3 to the right global with a small if/else ladder:\n"
        " *       get_key(i), set_key(i, x), get_val(i), set_val(i, x)\n"
        " *   Everything else (find, set, get, has, del) is written once, in terms of\n"
        " *   those accessors, so the four-slot limit lives in exactly one place. This is\n"
        " *   the standard way to express an indexed table in this compiler's scalar-only\n"
        " *   world; to grow the store you extend the ladders and the slot count together.\n"
        " *\n"
        " * COMPILER RULES THAT SHAPED THIS FILE:\n"
        " *   - NO #include / #define; self-contained, integers only.\n"
        " *   - GLOBALS START AT ZERO and initializers are ignored -> g_used and the slots\n"
        " *     begin empty automatically, and the self-test sets values at run time.\n"
        " *   - NO switch statement in the subset -> the accessors use if/else ladders.\n"
        " *   - NO stdin needed: the self-test is a fixed script.\n"
        " *\n"
        " * HOW TO EXTEND IT:\n"
        " *   - More slots: add k4/v4..., extend each accessor ladder by one line, and\n"
        " *     raise the \"< 4\" bounds in find()/first_free() to the new count.\n"
        " *   - String keys: store a char* per slot instead of an int and compare with a\n"
        " *     string-equality helper (see 01_login.c's streq).\n"
        " *\n"
        " * Exit code = number of failed self-test checks (0 means all passed).\n"
        " * ==========================================================================*/\n"
        "\n"
        "/* On-device builtin (prototype only for the host syntax check; see 01_login.c). */\n"
        "void sys_write(int fd, char *buf, int len);\n"
        "\n"
        "/* ---- output layer --------------------------------------------------------- */\n"
        "char g_ch;\n"
        "/* emit: write a single character to stdout. */\n"
        "void emit(int c) { g_ch = c; sys_write(1, &g_ch, 1); }\n"
        "/* puts0: write a NUL-terminated string. */\n"
        "void puts0(char *s) { int n = 0; while (s[n]) n = n + 1; sys_write(1, s, n); }\n"
        "/* puti: print a signed integer in decimal. */\n"
        "void putu(int v) { if (v >= 10) putu(v / 10); emit('0' + v % 10); }\n"
        "void puti(int v) { if (v < 0) { emit('-'); v = 0 - v; } putu(v); }\n"
        "\n"
        "/* ---- the four slots, as plain scalar globals ----------------------------- */\n"
        "int k0; int k1; int k2; int k3;     /* the keys   (start at 0) */\n"
        "int v0; int v1; int v2; int v3;     /* the values (start at 0) */\n"
        "int g_used;                          /* bit i set => slot i holds a pair */\n"
        "\n"
        "/* get_key: return the key stored in slot i (0..3). */\n"
        "int get_key(int i) {\n"
        "    if (i == 0) return k0;\n"
        "    if (i == 1) return k1;\n"
        "    if (i == 2) return k2;\n"
        "    return k3;\n"
        "}\n"
        "/* set_key: store key x into slot i (0..3). */\n"
        "void set_key(int i, int x) {\n"
        "    if (i == 0) k0 = x;\n"
        "    else if (i == 1) k1 = x;\n"
        "    else if (i == 2) k2 = x;\n"
        "    else k3 = x;\n"
        "}\n"
        "/* get_val: return the value stored in slot i (0..3). */\n"
        "int get_val(int i) {\n"
        "    if (i == 0) return v0;\n"
        "    if (i == 1) return v1;\n"
        "    if (i == 2) return v2;\n"
        "    return v3;\n"
        "}\n"
        "/* set_val: store value x into slot i (0..3). */\n"
        "void set_val(int i, int x) {\n"
        "    if (i == 0) v0 = x;\n"
        "    else if (i == 1) v1 = x;\n"
        "    else if (i == 2) v2 = x;\n"
        "    else v3 = x;\n"
        "}\n"
        "\n"
        "/* slot_used: 1 if slot i currently holds a pair, else 0. */\n"
        "int slot_used(int i) { return (g_used >> i) & 1; }\n"
        "\n"
        "/* find: return the slot index holding `key`, or -1 if the key is not present. */\n"
        "int find(int key) {\n"
        "    int i = 0;\n"
        "    while (i < 4) {\n"
        "        if (slot_used(i) && get_key(i) == key) return i;\n"
        "        i = i + 1;\n"
        "    }\n"
        "    return -1;\n"
        "}\n"
        "\n"
        "/* first_free: return the index of the first empty slot, or -1 if the store is full. */\n"
        "int first_free(void) {\n"
        "    int i = 0;\n"
        "    while (i < 4) {\n"
        "        if (!slot_used(i)) return i;\n"
        "        i = i + 1;\n"
        "    }\n"
        "    return -1;\n"
        "}\n"
        "\n"
        "/* kv_set: insert or overwrite (key -> val). Returns 1 on success, 0 if full. */\n"
        "int kv_set(int key, int val) {\n"
        "    int i = find(key);             /* overwrite if the key already exists */\n"
        "    if (i < 0) i = first_free();   /* otherwise take an empty slot */\n"
        "    if (i < 0) return 0;           /* store is full */\n"
        "    set_key(i, key);\n"
        "    set_val(i, val);\n"
        "    g_used = g_used | (1 << i);    /* mark the slot occupied */\n"
        "    return 1;\n"
        "}\n"
        "\n"
        "/* kv_has: 1 if `key` is present, else 0. */\n"
        "int kv_has(int key) { return find(key) >= 0; }\n"
        "\n"
        "/* kv_get: the value for `key`, or 0 if the key is absent (use kv_has to tell\n"
        " * a real stored 0 from a missing key). */\n"
        "int kv_get(int key) {\n"
        "    int i = find(key);\n"
        "    if (i < 0) return 0;\n"
        "    return get_val(i);\n"
        "}\n"
        "\n"
        "/* kv_del: remove `key` if present (clearing its occupied bit frees the slot). */\n"
        "void kv_del(int key) {\n"
        "    int i = find(key);\n"
        "    if (i >= 0) g_used = g_used & (~(1 << i));\n"
        "}\n"
        "\n"
        "/* ---- the self-test -------------------------------------------------------- */\n"
        "int g_fails;      /* number of failed checks (start at 0) */\n"
        "\n"
        "/* check: print \"PASS name\" if cond is true, else \"FAIL name\" and count it.\n"
        " *   Contract: cond is the already-computed truth of the thing being asserted. */\n"
        "void check(int cond, char *name) {\n"
        "    if (cond) {\n"
        "        puts0(\"  PASS  \");\n"
        "    } else {\n"
        "        puts0(\"  FAIL  \");\n"
        "        g_fails = g_fails + 1;\n"
        "    }\n"
        "    puts0(name);\n"
        "    emit('\\n');\n"
        "}\n"
        "\n"
        "/* main: exercise the store against known-good answers and report.\n"
        " *\n"
        " * The script, numbered:\n"
        " *   1. start empty: nothing is present.\n"
        " *   2. set three pairs; confirm get/has for each.\n"
        " *   3. overwrite an existing key; confirm the new value replaced the old.\n"
        " *   4. delete a key; confirm it is gone but the others remain.\n"
        " *   5. fill the store and prove a fifth distinct key is rejected (full).\n"
        " *   6. print a summary and return the failure count.\n"
        " */\n"
        "int main(void) {\n"
        "    /* step 1 */\n"
        "    g_used  = 0;\n"
        "    g_fails = 0;\n"
        "    puts0(\"== AutomationOS key/value store self-test ==\\n\\n\");\n"
        "    check(kv_has(10) == 0, \"empty store has no key 10\");\n"
        "\n"
        "    /* step 2 */\n"
        "    kv_set(10, 100);\n"
        "    kv_set(20, 200);\n"
        "    kv_set(30, 300);\n"
        "    check(kv_get(10) == 100, \"get(10) == 100\");\n"
        "    check(kv_get(20) == 200, \"get(20) == 200\");\n"
        "    check(kv_has(30) == 1,   \"has(30) is true\");\n"
        "    check(kv_has(99) == 0,   \"has(99) is false\");\n"
        "\n"
        "    /* step 3 */\n"
        "    kv_set(20, 222);\n"
        "    check(kv_get(20) == 222, \"overwrite: get(20) == 222\");\n"
        "\n"
        "    /* step 4 */\n"
        "    kv_del(10);\n"
        "    check(kv_has(10) == 0,   \"after delete: has(10) is false\");\n"
        "    check(kv_get(30) == 300, \"delete left get(30) == 300\");\n"
        "\n"
        "    /* step 5 -- three slots are full (20,30 plus two fresh), prove rejection */\n"
        "    kv_set(40, 400);          /* now slots hold 20,30,40 ... and one freed by del(10) */\n"
        "    kv_set(50, 500);          /* fills the fourth slot: 20,30,40,50 */\n"
        "    check(kv_set(60, 600) == 0, \"full store rejects a 5th key\");\n"
        "    check(kv_has(60) == 0,      \"rejected key 60 is absent\");\n"
        "\n"
        "    /* step 6 */\n"
        "    puts0(\"\\nresult: \");\n"
        "    if (g_fails == 0) puts0(\"ALL CHECKS PASSED\");\n"
        "    else { puts0(\"FAILURES = \"); puti(g_fails); }\n"
        "    emit('\\n');\n"
        "    return g_fails;\n"
        "}\n"
    },
};

enum { IDE_TEMPLATES_COUNT = (int)(sizeof(IDE_TEMPLATES) / sizeof(IDE_TEMPLATES[0])) };

#endif /* IDE_TEMPLATES_H */
