/*
 * mathtest.c -- boot-time known-answer-test battery for the fpm fixed-point
 * ========================================================================
 * math library (userspace/lib/fpm). Cryptotest-style: bare _start, own syscalls,
 * NO libc, NO floating point. Runs a COMPACT subset of the host KAT sweep on the
 * device -- table init, then 32 spot values per scalar function family plus a
 * vector normalize and a matrix inverse round-trip -- comparing against expected
 * Q16.16 integer constants precomputed on the host.
 *
 * WHY EXACT EQUALITY: fpm is integer-only and deterministic, and the device
 * links the SAME fpm.c the host generator ran (the freestanding pragmas change
 * only instruction selection / the canary, never integer results). So each
 * on-device result must equal the embedded expected value BIT-FOR-BIT. A wrong
 * or stubbed function diverges by thousands and is caught. The embedded tables
 * were generated by scratchpad/gen_mathtest.c (which #includes fpm.c) -- see the
 * MATH-0a report for the exact command.
 *
 * Prints one "[MATHTEST] <name>: PASS/FAIL" per family and a final
 * "MATHTEST: PASS n=<checks>" summary that build_test/mathtest_check.sh greps.
 */
/* Same freestanding gcc-15 pins as userspace/lib/fpm/fpm.c (see the rationale
 * block there): no auto-vectorizer xmm, no synthesized libc calls, no
 * re-injected %fs:0x28 canary (_start keeps fxm4 16-int locals on the stack,
 * which trips the stack-protector self-spec and would leave an undefined
 * __stack_chk_fail in this libc-free link), and no-sse so the by-value fxm4
 * copies expand to integer mov pairs instead of movdqa. Pragmas BEFORE the
 * include so fpm.h's static-inline vector helpers inherit them too. */
#pragma GCC optimize("no-tree-vectorize")
#pragma GCC optimize("no-tree-loop-distribute-patterns")
#pragma GCC optimize("no-stack-protector")
#pragma GCC target("no-sse")

#include "../../lib/fpm/fpm.h"

#define SYS_EXIT  0
#define SYS_WRITE 3

static long sc(long n, long a1, long a2, long a3) {
    long r;
    asm volatile("syscall" : "=a"(r) : "a"(n), "D"(a1), "S"(a2), "d"(a3)
                 : "rcx", "r11", "memory");
    return r;
}
static unsigned long slen(const char *s) { unsigned long n = 0; while (s[n]) n++; return n; }
static void print(const char *m) { sc(SYS_WRITE, 1, (long)m, (long)slen(m)); }
static void print_uint(unsigned int v) {
    char buf[12]; int i = 12;
    if (v == 0) { print("0"); return; }
    while (v && i > 0) { buf[--i] = (char)('0' + (v % 10)); v /= 10; }
    sc(SYS_WRITE, 1, (long)(buf + i), (long)(12 - i));
}
static void report(const char *name, int fails) {
    print("[MATHTEST] "); print(name); print(fails == 0 ? ": PASS\n" : ": FAIL\n");
}

/* ===== AUTO-GENERATED embedded KAT tables (scratchpad/gen_mathtest.c) ===== */
static const fx MUL_A[32] = {
    -262144,-245760,-229376,-212992,-196608,-180224,-163840,-147456,
    -131072,-114688,-98304,-81920,-65536,-49152,-32768,-16384,
    0,16384,32768,49152,65536,81920,98304,114688,
    131072,147456,163840,180224,196608,212992,229376,245760,
};
static const fx MUL_B[32] = {
    -374491,-346404,-318317,-290230,-262144,-234057,-205970,-177883,
    -149796,-121709,-93622,-65536,-37449,-9362,18724,46811,
    74898,102985,131072,159158,187245,215332,243419,271506,
    299593,327680,355766,383853,411940,440027,468114,496201,
};
static const fx MUL_E[32] = {
    1497964,1299015,1114109,943247,786432,643656,514925,400236,
    299592,212990,140433,81920,37449,7021,-9362,-11703,
    0,25746,65536,119368,187245,269165,365128,475135,
    599186,737280,889415,1055595,1235820,1430087,1638399,1860753,
};
static const fx DIV_A[32] = {
    -1310720,-1201493,-1092266,-983040,-873813,-764586,-655360,-546133,
    -436906,-327680,-218453,-109226,0,109226,218453,327680,
    436906,546133,655360,764586,873813,983040,1092266,1201493,
    1310720,1419946,1529173,1638400,1747626,1856853,1966080,2075306,
};
static const fx DIV_B[32] = {
    -122880,-114688,-106496,-98304,-90112,-81920,-73728,-65536,
    -57344,-49152,-40960,-32768,-24576,-16384,-8192,0,
    8192,16384,24576,32768,40960,49152,57344,65536,
    73728,81920,90112,98304,106496,114688,122880,131072,
};
static const fx DIV_E[32] = {
    699050,686567,672163,655360,635500,611668,582542,546133,
    499321,436906,349524,218452,0,-436904,-1747624,2147483647,
    3495248,2184532,1747626,1529172,1398100,1310720,1248304,1201493,
    1165084,1135956,1112125,1092266,1075462,1061058,1048576,1037653,
};
static const fx SQRT_I[32] = {
    16384,32768,81920,163840,278528,425984,606208,819200,
    1064960,1343488,1654784,1998848,2375680,2785280,3227648,3702784,
    4210688,4751360,5324800,5931008,6569984,7241728,7946240,8683520,
    9453568,10256384,11091968,11960320,12861440,13795328,14761984,15761408,
};
static const fx SQRT_E[32] = {
    32768,46340,73271,103621,135105,167084,199319,231704,
    264184,296726,329314,361934,394578,427242,459920,492611,
    525311,558018,590733,623453,656178,688907,721640,754376,
    787114,819855,852597,885342,918088,950836,983585,1016336,
};
static const fx RSQRT_I[32] = {
    2048,63423983,126845918,190267853,253689788,317111723,380533658,443955593,
    507377528,570799463,634221398,697643333,761065268,824487203,887909138,951331073,
    1014753008,1078174943,1141596878,1205018813,1268440748,1331862683,1395284618,1458706553,
    1522128488,1585550423,1648972358,1712394293,1775816228,1839238163,1902660098,1966082033,
};
static const fx RSQRT_E[32] = {
    370737,2106,1489,1216,1053,942,860,796,
    744,702,666,635,608,584,563,543,
    526,510,496,483,471,459,449,439,
    430,421,413,405,398,391,384,378,
};
static const int SIN_B[32] = {
    0,32,64,96,128,160,192,224,
    256,288,320,352,384,416,448,480,
    512,544,576,608,640,672,704,736,
    768,800,832,864,896,928,960,992,
};
static const fx SIN_E[32] = {
    0,12784,25078,36409,46340,54490,60547,64276,
    65536,64276,60547,54491,46341,36409,25079,12785,
    0,-12785,-25079,-36409,-46341,-54491,-60547,-64276,
    -65536,-64276,-60547,-54491,-46341,-36409,-25079,-12785,
};
static const fx COS_E[32] = {
    65536,64276,60547,54491,46341,36409,25079,12785,
    0,-12785,-25079,-36409,-46341,-54491,-60547,-64276,
    -65536,-64276,-60547,-54491,-46341,-36409,-25079,-12785,
    0,12784,25078,36409,46340,54490,60547,64276,
};
static const fx ATAN_Y[32] = {
    -196608,-131072,-65536,0,65536,131072,196608,-196608,
    -131072,-65536,0,65536,131072,196608,-196608,-131072,
    -65536,0,65536,131072,196608,-196608,-131072,-65536,
    0,65536,131072,196608,-196608,-131072,-65536,0,
};
static const fx ATAN_X[32] = {
    -262144,-131072,0,131072,262144,-196608,-65536,65536,
    196608,-262144,-131072,0,131072,262144,-196608,-65536,
    65536,196608,-262144,-131072,0,131072,262144,-196608,
    -65536,65536,196608,-262144,-131072,0,131072,262144,
};
static const fx ATAN_E[32] = {
    -26681197,-25165989,-16777403,187,2616449,27274211,20213531,-13340901,
    -6280221,-30937983,33554619,16777403,8388443,6873235,-25165989,-21729179,
    -8388773,187,30937983,25165659,16777403,-10496995,-4951963,-30118117,
    33554619,8388443,6280221,26681197,-23057437,-16777403,-4951963,187,
};
static const fx ASIN_I[32] = {
    -65536,-61440,-57344,-53248,-49152,-45056,-40960,-36864,
    -32768,-28672,-24576,-20480,-16384,-12288,-8192,-4096,
    0,4096,8192,12288,16384,20480,24576,28672,
    32768,36864,40960,45056,49152,53248,57344,61440,
};
static const fx ASIN_E[32] = {
    -16777216,-12981315,-11380219,-10130005,-9058057,-8096421,-7211543,-6380613,
    -5592561,-4835927,-4105365,-3394595,-2699237,-2014303,-1338501,-667793,
    187,667793,1338501,2014303,2698585,3394595,4105365,4835927,
    5592561,6380613,7210891,8096421,9058057,10130005,11379567,12981315,
};
static const fx ACOS_E[32] = {
    33554432,29758531,28156783,26907221,25835273,24873637,23988107,23157829,
    22369777,21613143,20882581,20171811,19475801,18791519,18115717,17445009,
    16777403,16109423,15438715,14762913,14077979,13382621,12671851,11941289,
    11184655,10396603,9565673,8680795,7719159,6647211,5396997,3795901,
};
static const fx NORM_IN[3]  = { 196608, -262144, 786432 };
static const fx NORM_EXP[3] = { 15123, -20164, 60492 };
static const fx LEN_EXP     = 851968;
/* ===== end AUTO-GENERATED ===== */

void _start(void)
{
    fpm_init();                 /* build the sine table before any trig KAT */
    int checks = 0, fails = 0, f;

    /* fx_mul */
    f = 0; for (int i = 0; i < 32; i++) { checks++; if (fx_mul(MUL_A[i], MUL_B[i]) != MUL_E[i]) f++; }
    report("fx_mul (32 KAT, exact)", f); fails += f;

    /* fx_div (incl. one /0 -> saturate case at index 15) */
    f = 0; for (int i = 0; i < 32; i++) { checks++; if (fx_div(DIV_A[i], DIV_B[i]) != DIV_E[i]) f++; }
    report("fx_div (32 KAT, incl /0 sat)", f); fails += f;

    /* fx_sqrt */
    f = 0; for (int i = 0; i < 32; i++) { checks++; if (fx_sqrt(SQRT_I[i]) != SQRT_E[i]) f++; }
    report("fx_sqrt (32 KAT)", f); fails += f;

    /* fx_rsqrt */
    f = 0; for (int i = 0; i < 32; i++) { checks++; if (fx_rsqrt(RSQRT_I[i]) != RSQRT_E[i]) f++; }
    report("fx_rsqrt (32 KAT)", f); fails += f;

    /* fx_sin */
    f = 0; for (int i = 0; i < 32; i++) { checks++; if (fx_sin(SIN_B[i]) != SIN_E[i]) f++; }
    report("fx_sin (32 KAT)", f); fails += f;

    /* fx_cos */
    f = 0; for (int i = 0; i < 32; i++) { checks++; if (fx_cos(SIN_B[i]) != COS_E[i]) f++; }
    report("fx_cos (32 KAT)", f); fails += f;

    /* fx_atan2 (all quadrants + axes) */
    f = 0; for (int i = 0; i < 32; i++) { checks++; if (fx_atan2(ATAN_Y[i], ATAN_X[i]) != ATAN_E[i]) f++; }
    report("fx_atan2 (32 KAT)", f); fails += f;

    /* fx_asin */
    f = 0; for (int i = 0; i < 32; i++) { checks++; if (fx_asin(ASIN_I[i]) != ASIN_E[i]) f++; }
    report("fx_asin (32 KAT)", f); fails += f;

    /* fx_acos */
    f = 0; for (int i = 0; i < 32; i++) { checks++; if (fx_acos(ASIN_I[i]) != ACOS_E[i]) f++; }
    report("fx_acos (32 KAT)", f); fails += f;

    /* fxv3 normalize + len */
    f = 0;
    { fxv3 v = fxv3_mk(NORM_IN[0], NORM_IN[1], NORM_IN[2]);
      fxv3 n = fxv3_normalize(v);
      checks++; if (n.x != NORM_EXP[0]) f++;
      checks++; if (n.y != NORM_EXP[1]) f++;
      checks++; if (n.z != NORM_EXP[2]) f++;
      checks++; if (fxv3_len(v) != LEN_EXP) f++; }
    report("fxv3 normalize+len (4 KAT)", f); fails += f;

    /* fxm4 inverse-affine round-trip: M * M^-1 ~= I (tolerance 0.01 in fx) */
    f = 0;
    { fxm4 M = fxm4_mul(fxm4_translate(fx_from_int(3), fx_from_int(-2), fx_from_int(5)),
                        fxm4_mul(fxm4_rotate_y(fpm_deg(37)),
                                 fxm4_scale(fx_from_int(2), fx_ratio(1,2), fx_from_int(3))));
      fxm4 Mi = fxm4_inverse_affine(M);
      fxm4 I  = fxm4_mul(M, Mi);
      const fx TOL = 655;   /* 0.01 in Q16.16 */
      for (int c = 0; c < 4; c++) for (int r = 0; r < 4; r++) {
          fx want = (c == r) ? FX_ONE : 0;
          fx d = I.m[c*4+r] - want; if (d < 0) d = -d;
          checks++; if (d > TOL) f++;
      } }
    report("fxm4_inverse_affine roundtrip (16)", f); fails += f;

    print("MATHTEST: ");
    if (fails == 0) { print("PASS n="); print_uint((unsigned)checks); print("\n"); }
    else            { print("FAIL fails="); print_uint((unsigned)fails);
                      print(" of "); print_uint((unsigned)checks); print("\n"); }

    sc(SYS_EXIT, 0, 0, 0);
    for (;;) {}
}
